"""Aggregate shortcuts on Expr, one real method per function.

Generated by scripts/gen_aggregates.py. Do not edit; regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class AggregateMethods:
    """The aggregate functions reachable as methods, so `col("v").sum()` reads as SQL does.

    Each becomes a window function with `.over()`. Anything not here is a
    `fn()` call away.
    """

    #: Method name to SQL function, the table these methods were written from.
    _CALLABLES: ClassVar[dict[str, str]] = {
        "sum": "sum",
        "mean": "avg",
        "avg": "avg",
        "min": "min",
        "max": "max",
        "count": "count",
        "median": "median",
        "std": "stddev_samp",
        "var": "var_samp",
        "first": "first",
        "last": "last",
        "any_value": "any_value",
        "bit_and": "bit_and",
        "bit_or": "bit_or",
        "bool_and": "bool_and",
        "bool_or": "bool_or",
        "product": "product",
        "string_agg": "string_agg",
        "skewness": "skewness",
        "kurtosis": "kurtosis",
        "entropy": "entropy",
        "array_agg": "array_agg",
        "mode": "mode",
        "quantile": "quantile_cont",
        "arg_min": "arg_min",
        "arg_max": "arg_max",
    }

    def _call(self, function: str, *args: object) -> Expr:  # pragma: no cover - Expr defines it
        raise NotImplementedError

    def sum(self, *args: object) -> Expr:
        """The sum of the values. SQL: `sum`."""
        return self._call("sum", *args)

    def mean(self, *args: object) -> Expr:
        """The average of the values. SQL: `avg`."""
        return self._call("avg", *args)

    def avg(self, *args: object) -> Expr:
        """The average of the values. The same as `mean`. SQL: `avg`."""
        return self._call("avg", *args)

    def min(self, *args: object) -> Expr:
        """The smallest value. SQL: `min`."""
        return self._call("min", *args)

    def max(self, *args: object) -> Expr:
        """The largest value. SQL: `max`."""
        return self._call("max", *args)

    def count(self, *args: object) -> Expr:
        """How many values are not NULL. For rows, use `count_all()`. SQL: `count`."""
        return self._call("count", *args)

    def median(self, *args: object) -> Expr:
        """The middle value. SQL: `median`."""
        return self._call("median", *args)

    def std(self, *args: object) -> Expr:
        """The sample standard deviation. SQL: `stddev_samp`."""
        return self._call("stddev_samp", *args)

    def var(self, *args: object) -> Expr:
        """The sample variance. SQL: `var_samp`."""
        return self._call("var_samp", *args)

    def first(self, *args: object) -> Expr:
        """The first value seen. Order it with `.over()` or `sort` to make that mean something. SQL: `first`."""
        return self._call("first", *args)

    def last(self, *args: object) -> Expr:
        """The last value seen. SQL: `last`."""
        return self._call("last", *args)

    def any_value(self, *args: object) -> Expr:
        """Any one of the values, whichever is cheapest. SQL: `any_value`."""
        return self._call("any_value", *args)

    def bit_and(self, *args: object) -> Expr:
        """The bitwise AND of the values. SQL: `bit_and`."""
        return self._call("bit_and", *args)

    def bit_or(self, *args: object) -> Expr:
        """The bitwise OR of the values. SQL: `bit_or`."""
        return self._call("bit_or", *args)

    def bool_and(self, *args: object) -> Expr:
        """Whether every value is true. SQL: `bool_and`."""
        return self._call("bool_and", *args)

    def bool_or(self, *args: object) -> Expr:
        """Whether any value is true. SQL: `bool_or`."""
        return self._call("bool_or", *args)

    def product(self, *args: object) -> Expr:
        """The product of the values. SQL: `product`."""
        return self._call("product", *args)

    def string_agg(self, *args: object) -> Expr:
        """The values joined as text. Pass the separator as an argument. SQL: `string_agg`."""
        return self._call("string_agg", *args)

    def skewness(self, *args: object) -> Expr:
        """The skewness of the distribution. SQL: `skewness`."""
        return self._call("skewness", *args)

    def kurtosis(self, *args: object) -> Expr:
        """The kurtosis of the distribution. SQL: `kurtosis`."""
        return self._call("kurtosis", *args)

    def entropy(self, *args: object) -> Expr:
        """The entropy of the distribution. SQL: `entropy`."""
        return self._call("entropy", *args)

    def array_agg(self, *args: object) -> Expr:
        """The values gathered into a list. SQL: `array_agg`."""
        return self._call("array_agg", *args)

    def mode(self, *args: object) -> Expr:
        """The most frequent value. SQL: `mode`."""
        return self._call("mode", *args)

    def quantile(self, *args: object) -> Expr:
        """The value at a quantile, interpolated. Pass the quantile, 0 to 1. SQL: `quantile_cont`."""
        return self._call("quantile_cont", *args)

    def arg_min(self, *args: object) -> Expr:
        """The value of the argument where this is smallest. SQL: `arg_min`."""
        return self._call("arg_min", *args)

    def arg_max(self, *args: object) -> Expr:
        """The value of the argument where this is largest. SQL: `arg_max`."""
        return self._call("arg_max", *args)
