"""The function namespaces: `.str()`, `.dt()`, `.list()` and `.json()` on an expression.

Generated by scripts/gen_func_namespaces.py from func_namespaces.toml,
checked against duckdb_functions(). Do not edit; regenerate after bumping
engine.pin or changing the table.

A family class is a method scope, not a type: entering one says how the
expression is meant, and the engine still judges every call. The two
reasons the families exist: without them every method would sit on every
expression (several hundred names after each dot), and the family prefix
could not be dropped (`.list().min()` can mean `list_min` only because
`.min()` still means the aggregate).
"""

from __future__ import annotations

from typing import ClassVar

from .expr import Expr, FamilyExpr


class StrExpr(FamilyExpr):
    """Text functions, applied to this expression as the string."""

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "ascii": ("ascii", 0, ["VARCHAR"]),
        "bin": ("bin", 0, ["VARCHAR"]),
        "bit_length": ("bit_length", 0, ["VARCHAR"]),
        "concat_ws": ("concat_ws", 1, ["VARCHAR", "ANY"]),
        "contains": ("contains", 0, ["VARCHAR", "VARCHAR"]),
        "damerau_levenshtein": ("damerau_levenshtein", 0, ["VARCHAR", "VARCHAR"]),
        "format": ("format", 0, ["VARCHAR"]),
        "from_base64": ("from_base64", 0, ["VARCHAR"]),
        "hamming": ("hamming", 0, ["VARCHAR", "VARCHAR"]),
        "ilike_escape": ("ilike_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "instr": ("instr", 0, ["VARCHAR", "VARCHAR"]),
        "jaccard": ("jaccard", 0, ["VARCHAR", "VARCHAR"]),
        "jaro_similarity": ("jaro_similarity", 0, ["VARCHAR", "VARCHAR"]),
        "jaro_winkler_similarity": ("jaro_winkler_similarity", 0, ["VARCHAR", "VARCHAR"]),
        "left": ("left", 0, ["VARCHAR", "BIGINT"]),
        "left_grapheme": ("left_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "length": ("length", 0, ["VARCHAR"]),
        "length_grapheme": ("length_grapheme", 0, ["VARCHAR"]),
        "levenshtein": ("levenshtein", 0, ["VARCHAR", "VARCHAR"]),
        "like_escape": ("like_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "lower": ("lower", 0, ["VARCHAR"]),
        "lpad": ("lpad", 0, ["VARCHAR", "INTEGER", "VARCHAR"]),
        "ltrim": ("ltrim", 0, ["VARCHAR"]),
        "md5": ("md5", 0, ["VARCHAR"]),
        "md5_number": ("md5_number", 0, ["VARCHAR"]),
        "nfc_normalize": ("nfc_normalize", 0, ["VARCHAR"]),
        "not_ilike_escape": ("not_ilike_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "not_like_escape": ("not_like_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "overlay": ("overlay", 0, ["VARCHAR", "VARCHAR", "BIGINT"]),
        "parse_dirname": ("parse_dirname", 0, ["VARCHAR"]),
        "parse_dirpath": ("parse_dirpath", 0, ["VARCHAR"]),
        "parse_filename": ("parse_filename", 0, ["VARCHAR"]),
        "parse_formatted_bytes": ("parse_formatted_bytes", 0, ["VARCHAR"]),
        "parse_path": ("parse_path", 0, ["VARCHAR"]),
        "path_join": ("path_join", 0, ["VARCHAR"]),
        "prefix": ("prefix", 0, ["VARCHAR", "VARCHAR"]),
        "printf": ("printf", 0, ["VARCHAR"]),
        "regexp_escape": ("regexp_escape", 0, ["VARCHAR"]),
        "regexp_extract": ("regexp_extract", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_extract_all": ("regexp_extract_all", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_full_match": ("regexp_full_match", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_matches": ("regexp_matches", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_replace": ("regexp_replace", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "replace": ("replace", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "reverse": ("reverse", 0, ["VARCHAR"]),
        "right": ("right", 0, ["VARCHAR", "BIGINT"]),
        "right_grapheme": ("right_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "rpad": ("rpad", 0, ["VARCHAR", "INTEGER", "VARCHAR"]),
        "rtrim": ("rtrim", 0, ["VARCHAR"]),
        "sha1": ("sha1", 0, ["VARCHAR"]),
        "sha256": ("sha256", 0, ["VARCHAR"]),
        "string_split": ("string_split", 0, ["VARCHAR", "VARCHAR"]),
        "string_split_regex": ("string_split_regex", 0, ["VARCHAR", "VARCHAR"]),
        "strip_accents": ("strip_accents", 0, ["VARCHAR"]),
        "strlen": ("strlen", 0, ["VARCHAR"]),
        "substring": ("substring", 0, ["VARCHAR", "BIGINT"]),
        "substring_grapheme": ("substring_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "suffix": ("suffix", 0, ["VARCHAR", "VARCHAR"]),
        "translate": ("translate", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "trim": ("trim", 0, ["VARCHAR"]),
        "unbin": ("unbin", 0, ["VARCHAR"]),
        "unhex": ("unhex", 0, ["VARCHAR"]),
        "unicode": ("unicode", 0, ["VARCHAR"]),
        "upper": ("upper", 0, ["VARCHAR"]),
        "url_decode": ("url_decode", 0, ["VARCHAR"]),
        "url_encode": ("url_encode", 0, ["VARCHAR"]),
    }

    def ascii(self, *args: object) -> Expr:
        """Returns an integer that represents the Unicode code point of the firs... SQL: `ascii`."""
        return self._call("ascii", *args)

    def bin(self, *args: object) -> StrExpr:
        """Converts the `string` to binary representation. SQL: `bin`."""
        return StrExpr(self._call("bin", *args))

    def bit_length(self, *args: object) -> Expr:
        """Number of bits in a `string`. SQL: `bit_length`."""
        return self._call("bit_length", *args)

    def concat_ws(self, separator: object, *args: object) -> StrExpr:
        """Concatenates many strings, separated by `separator`. Arguments: separator. SQL: `concat_ws`."""
        return StrExpr(self._call_at("concat_ws", 1, separator, *args))

    def contains(self, *args: object) -> Expr:
        """Returns `true` if `search_string` is found within `string`. Arguments: search_string. SQL: `contains`."""
        return self._call("contains", *args)

    def damerau_levenshtein(self, *args: object) -> Expr:
        """Extension of Levenshtein distance to also include transposition of ad...

        Arguments: s2. SQL: `damerau_levenshtein`.
        """
        return self._call("damerau_levenshtein", *args)

    def format(self, *args: object) -> StrExpr:
        """Formats a string using the fmt syntax. SQL: `format`."""
        return StrExpr(self._call("format", *args))

    def from_base64(self, *args: object) -> Expr:
        """Converts a base64 encoded `string` to a character string (`BLOB`). SQL: `from_base64`."""
        return self._call("from_base64", *args)

    def hamming(self, *args: object) -> Expr:
        """The number of positions with different characters, for two strings of equal length.

        Arguments: s2. SQL: `hamming`.
        """
        return self._call("hamming", *args)

    def ilike_escape(self, *args: object) -> Expr:
        """Returns `true` if the `string` matches the `like_specifier` (see Patt...

        Arguments: like_specifier, escape_character. SQL: `ilike_escape`.
        """
        return self._call("ilike_escape", *args)

    def instr(self, *args: object) -> Expr:
        """Returns location of first occurrence of `search_string` in `string`,...

        Arguments: search_string. SQL: `instr`.
        """
        return self._call("instr", *args)

    def jaccard(self, *args: object) -> Expr:
        """The Jaccard similarity between two strings. Arguments: s2. SQL: `jaccard`."""
        return self._call("jaccard", *args)

    def jaro_similarity(self, *args: object) -> Expr:
        """The Jaro similarity between two strings. Arguments: s2. SQL: `jaro_similarity`."""
        return self._call("jaro_similarity", *args)

    def jaro_winkler_similarity(self, *args: object) -> Expr:
        """The Jaro-Winkler similarity between two strings. Arguments: s2. SQL: `jaro_winkler_similarity`."""
        return self._call("jaro_winkler_similarity", *args)

    def left(self, *args: object) -> StrExpr:
        """Extracts the left-most count characters. Arguments: count. SQL: `left`."""
        return StrExpr(self._call("left", *args))

    def left_grapheme(self, *args: object) -> StrExpr:
        """Extracts the left-most count grapheme clusters. Arguments: count. SQL: `left_grapheme`."""
        return StrExpr(self._call("left_grapheme", *args))

    def length(self, *args: object) -> Expr:
        """Number of characters in `string`. SQL: `length`."""
        return self._call("length", *args)

    def length_grapheme(self, *args: object) -> Expr:
        """Number of grapheme clusters in `string`. SQL: `length_grapheme`."""
        return self._call("length_grapheme", *args)

    def levenshtein(self, *args: object) -> Expr:
        """The minimum number of single-character edits (insertions, deletions o...

        Arguments: s2. SQL: `levenshtein`.
        """
        return self._call("levenshtein", *args)

    def like_escape(self, *args: object) -> Expr:
        """Returns `true` if the `string` matches the `like_specifier` (see Patt...

        Arguments: like_specifier, escape_character. SQL: `like_escape`.
        """
        return self._call("like_escape", *args)

    def lower(self, *args: object) -> StrExpr:
        """Converts `string` to lower case. SQL: `lower`."""
        return StrExpr(self._call("lower", *args))

    def lpad(self, *args: object) -> StrExpr:
        """Pads the `string` with the `character` on the left until it has `coun...

        Arguments: count, character. SQL: `lpad`.
        """
        return StrExpr(self._call("lpad", *args))

    def ltrim(self, *args: object) -> StrExpr:
        """Removes any occurrences of any of the `characters` from the left side... SQL: `ltrim`."""
        return StrExpr(self._call("ltrim", *args))

    def md5(self, *args: object) -> StrExpr:
        """Returns the MD5 hash of the `string` as a `VARCHAR`. SQL: `md5`."""
        return StrExpr(self._call("md5", *args))

    def md5_number(self, *args: object) -> Expr:
        """Returns the MD5 hash of the `string` as a `HUGEINT`. SQL: `md5_number`."""
        return self._call("md5_number", *args)

    def nfc_normalize(self, *args: object) -> StrExpr:
        """Converts `string` to Unicode NFC normalized string. SQL: `nfc_normalize`."""
        return StrExpr(self._call("nfc_normalize", *args))

    def not_ilike_escape(self, *args: object) -> Expr:
        """Returns `false` if the `string` matches the `like_specifier` (see Pat...

        Arguments: like_specifier, escape_character. SQL: `not_ilike_escape`.
        """
        return self._call("not_ilike_escape", *args)

    def not_like_escape(self, *args: object) -> Expr:
        """Returns `false` if the `string` matches the `like_specifier` (see Pat...

        Arguments: like_specifier, escape_character. SQL: `not_like_escape`.
        """
        return self._call("not_like_escape", *args)

    def overlay(self, *args: object) -> StrExpr:
        """Replaces a substring of `string` starting at character `start` with `...

        Arguments: replacement, start. SQL: `overlay`.
        """
        return StrExpr(self._call("overlay", *args))

    def parse_dirname(self, *args: object) -> StrExpr:
        """Returns the top-level directory name from the given `path`. SQL: `parse_dirname`."""
        return StrExpr(self._call("parse_dirname", *args))

    def parse_dirpath(self, *args: object) -> StrExpr:
        """Returns the head of the `path` (the pathname until the last slash) si... SQL: `parse_dirpath`."""
        return StrExpr(self._call("parse_dirpath", *args))

    def parse_filename(self, *args: object) -> StrExpr:
        """Returns the last component of the `path` similarly to Python's `os.pa... SQL: `parse_filename`."""
        return StrExpr(self._call("parse_filename", *args))

    def parse_formatted_bytes(self, *args: object) -> Expr:
        """Parses a human-readable representation of a size in bytes into an int... SQL: `parse_formatted_bytes`."""
        return self._call("parse_formatted_bytes", *args)

    def parse_path(self, *args: object) -> ListExpr:
        """Returns a list of the components (directories and filename) in the `p... SQL: `parse_path`."""
        return ListExpr(self._call("parse_path", *args))

    def path_join(self, *args: object) -> StrExpr:
        """Joins path components using the platform separator, normalizing dupli... SQL: `path_join`."""
        return StrExpr(self._call("path_join", *args))

    def prefix(self, *args: object) -> Expr:
        """Returns `true` if `string` starts with `search_string`. Arguments: search_string. SQL: `prefix`."""
        return self._call("prefix", *args)

    def printf(self, *args: object) -> StrExpr:
        """Formats a `string` using printf syntax. SQL: `printf`."""
        return StrExpr(self._call("printf", *args))

    def regexp_escape(self, *args: object) -> StrExpr:
        """Escapes special patterns to turn `string` into a regular expression s... SQL: `regexp_escape`."""
        return StrExpr(self._call("regexp_escape", *args))

    def regexp_extract(self, *args: object) -> StrExpr:
        """If `string` contains the `regex` pattern, returns the capturing group...

        Arguments: regex. SQL: `regexp_extract`.
        """
        return StrExpr(self._call("regexp_extract", *args))

    def regexp_extract_all(self, *args: object) -> ListExpr:
        """Finds non-overlapping occurrences of the `regex` in the `string` and...

        Arguments: regex. SQL: `regexp_extract_all`.
        """
        return ListExpr(self._call("regexp_extract_all", *args))

    def regexp_full_match(self, *args: object) -> Expr:
        """Returns `true` if the entire `string` matches the `regex`. Arguments: regex. SQL: `regexp_full_match`."""
        return self._call("regexp_full_match", *args)

    def regexp_matches(self, *args: object) -> Expr:
        """Returns `true` if `string` contains the `regex`, `false` otherwise.

        Arguments: regex. SQL: `regexp_matches`.
        """
        return self._call("regexp_matches", *args)

    def regexp_replace(self, *args: object) -> StrExpr:
        """If `string` contains the `regex`, replaces the matching part with `re...

        Arguments: regex, replacement. SQL: `regexp_replace`.
        """
        return StrExpr(self._call("regexp_replace", *args))

    def replace(self, *args: object) -> StrExpr:
        """Replaces any occurrences of the `source` with `target` in `string`.

        Arguments: source, target. SQL: `replace`.
        """
        return StrExpr(self._call("replace", *args))

    def reverse(self, *args: object) -> StrExpr:
        """Reverses the `string`. SQL: `reverse`."""
        return StrExpr(self._call("reverse", *args))

    def right(self, *args: object) -> StrExpr:
        """Extract the right-most `count` characters. Arguments: count. SQL: `right`."""
        return StrExpr(self._call("right", *args))

    def right_grapheme(self, *args: object) -> StrExpr:
        """Extracts the right-most `count` grapheme clusters. Arguments: count. SQL: `right_grapheme`."""
        return StrExpr(self._call("right_grapheme", *args))

    def rpad(self, *args: object) -> StrExpr:
        """Pads the `string` with the `character` on the right until it has `cou...

        Arguments: count, character. SQL: `rpad`.
        """
        return StrExpr(self._call("rpad", *args))

    def rtrim(self, *args: object) -> StrExpr:
        """Removes any occurrences of any of the `characters` from the right sid... SQL: `rtrim`."""
        return StrExpr(self._call("rtrim", *args))

    def sha1(self, *args: object) -> StrExpr:
        """Returns a `VARCHAR` with the SHA-1 hash of the `value`. SQL: `sha1`."""
        return StrExpr(self._call("sha1", *args))

    def sha256(self, *args: object) -> StrExpr:
        """Returns a `VARCHAR` with the SHA-256 hash of the `value`. SQL: `sha256`."""
        return StrExpr(self._call("sha256", *args))

    def string_split(self, *args: object) -> ListExpr:
        """Splits the `string` along the `separator`. Arguments: separator. SQL: `string_split`."""
        return ListExpr(self._call("string_split", *args))

    def string_split_regex(self, *args: object) -> ListExpr:
        """Splits the `string` along the `regex`. Arguments: regex. SQL: `string_split_regex`."""
        return ListExpr(self._call("string_split_regex", *args))

    def strip_accents(self, *args: object) -> StrExpr:
        """Strips accents from `string`. SQL: `strip_accents`."""
        return StrExpr(self._call("strip_accents", *args))

    def strlen(self, *args: object) -> Expr:
        """Number of bytes in `string`. SQL: `strlen`."""
        return self._call("strlen", *args)

    def substring(self, *args: object) -> StrExpr:
        """Extracts substring starting from character `start` up to the end of t...

        Arguments: start. SQL: `substring`.
        """
        return StrExpr(self._call("substring", *args))

    def substring_grapheme(self, *args: object) -> StrExpr:
        """Extracts substring starting from grapheme clusters `start` up to the...

        Arguments: start. SQL: `substring_grapheme`.
        """
        return StrExpr(self._call("substring_grapheme", *args))

    def suffix(self, *args: object) -> Expr:
        """Returns `true` if `string` ends with `search_string`. Arguments: search_string. SQL: `suffix`."""
        return self._call("suffix", *args)

    def translate(self, *args: object) -> StrExpr:
        """Replaces each character in `string` that matches a character in the `...

        Arguments: from, to. SQL: `translate`.
        """
        return StrExpr(self._call("translate", *args))

    def trim(self, *args: object) -> StrExpr:
        """Removes any occurrences of any of the `characters` from either side o... SQL: `trim`."""
        return StrExpr(self._call("trim", *args))

    def unbin(self, *args: object) -> Expr:
        """Converts a `value` from binary representation to a blob. SQL: `unbin`."""
        return self._call("unbin", *args)

    def unhex(self, *args: object) -> Expr:
        """Converts a `value` from hexadecimal representation to a blob. SQL: `unhex`."""
        return self._call("unhex", *args)

    def unicode(self, *args: object) -> Expr:
        """Returns an `INTEGER` representing the `unicode` codepoint of the firs... SQL: `unicode`."""
        return self._call("unicode", *args)

    def upper(self, *args: object) -> StrExpr:
        """Converts `string` to upper case. SQL: `upper`."""
        return StrExpr(self._call("upper", *args))

    def url_decode(self, *args: object) -> StrExpr:
        """Decodes a URL from a representation using Percent-Encoding. SQL: `url_decode`."""
        return StrExpr(self._call("url_decode", *args))

    def url_encode(self, *args: object) -> StrExpr:
        """Encodes a URL to a representation using Percent-Encoding. SQL: `url_encode`."""
        return StrExpr(self._call("url_encode", *args))


class DtExpr(FamilyExpr):
    """Date and time functions, applied to this expression as the date, time or timestamp."""

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "age": ("age", 0, ["TIMESTAMP"]),
        "century": ("century", 0, ["DATE"]),
        "day": ("day", 0, ["DATE"]),
        "dayname": ("dayname", 0, ["DATE"]),
        "dayofmonth": ("dayofmonth", 0, ["DATE"]),
        "dayofweek": ("dayofweek", 0, ["DATE"]),
        "dayofyear": ("dayofyear", 0, ["DATE"]),
        "days_in_month": ("days_in_month", 0, []),
        "decade": ("decade", 0, ["DATE"]),
        "diff": ("date_diff", 1, ["VARCHAR", "DATE", "DATE"]),
        "epoch": ("epoch", 0, ["DATE"]),
        "epoch_ns": ("epoch_ns", 0, ["DATE"]),
        "epoch_us": ("epoch_us", 0, ["DATE"]),
        "era": ("era", 0, ["DATE"]),
        "hour": ("hour", 0, ["DATE"]),
        "isodow": ("isodow", 0, ["DATE"]),
        "isoyear": ("isoyear", 0, ["DATE"]),
        "julian": ("julian", 0, ["DATE"]),
        "last_day": ("last_day", 0, ["DATE"]),
        "microsecond": ("microsecond", 0, ["DATE"]),
        "millennium": ("millennium", 0, ["DATE"]),
        "millisecond": ("millisecond", 0, ["DATE"]),
        "minute": ("minute", 0, ["DATE"]),
        "month": ("month", 0, ["DATE"]),
        "monthname": ("monthname", 0, ["DATE"]),
        "nanosecond": ("nanosecond", 0, ["DATE"]),
        "normalized_interval": ("normalized_interval", 0, ["INTERVAL"]),
        "part": ("date_part", 1, ["VARCHAR", "DATE"]),
        "quarter": ("quarter", 0, ["DATE"]),
        "second": ("second", 0, ["DATE"]),
        "strftime": ("strftime", 0, ["DATE", "VARCHAR"]),
        "sub": ("date_sub", 1, ["VARCHAR", "DATE", "DATE"]),
        "time_bucket": ("time_bucket", 1, ["INTERVAL", "DATE"]),
        "timetz_byte_comparable": ("timetz_byte_comparable", 0, ["TIME WITH TIME ZONE"]),
        "timezone": ("timezone", 0, ["TIMESTAMP"]),
        "timezone_hour": ("timezone_hour", 0, ["DATE"]),
        "timezone_minute": ("timezone_minute", 0, ["DATE"]),
        "trunc": ("date_trunc", 1, ["VARCHAR", "DATE"]),
        "week": ("week", 0, ["DATE"]),
        "weekday": ("weekday", 0, ["DATE"]),
        "weekofyear": ("weekofyear", 0, ["DATE"]),
        "year": ("year", 0, ["DATE"]),
        "yearweek": ("yearweek", 0, ["DATE"]),
    }

    def age(self, *args: object) -> DtExpr:
        """Subtract arguments, resulting in the time difference between the two... SQL: `age`."""
        return DtExpr(self._call("age", *args))

    def century(self, *args: object) -> Expr:
        """Extract the century component from a date or timestamp. SQL: `century`."""
        return self._call("century", *args)

    def day(self, *args: object) -> Expr:
        """Extract the day component from a date or timestamp. SQL: `day`."""
        return self._call("day", *args)

    def dayname(self, *args: object) -> StrExpr:
        """The (English) name of the weekday. SQL: `dayname`."""
        return StrExpr(self._call("dayname", *args))

    def dayofmonth(self, *args: object) -> Expr:
        """Extract the dayofmonth component from a date or timestamp. SQL: `dayofmonth`."""
        return self._call("dayofmonth", *args)

    def dayofweek(self, *args: object) -> Expr:
        """Extract the dayofweek component from a date or timestamp. SQL: `dayofweek`."""
        return self._call("dayofweek", *args)

    def dayofyear(self, *args: object) -> Expr:
        """Extract the dayofyear component from a date or timestamp. SQL: `dayofyear`."""
        return self._call("dayofyear", *args)

    def days_in_month(self, *args: object) -> Expr:
        """How many days the date's month has. SQL: `days_in_month`."""
        return self._call("days_in_month", *args)

    def decade(self, *args: object) -> Expr:
        """Extract the decade component from a date or timestamp. SQL: `decade`."""
        return self._call("decade", *args)

    def diff(self, part: object, *args: object) -> Expr:
        """The number of partition boundaries between the timestamps. Arguments: part, enddate. SQL: `date_diff`."""
        return self._call_at("date_diff", 1, part, *args)

    def epoch(self, *args: object) -> Expr:
        """Extract the epoch component from a temporal type. SQL: `epoch`."""
        return self._call("epoch", *args)

    def epoch_ns(self, *args: object) -> Expr:
        """Extract the epoch component in nanoseconds from a temporal type. SQL: `epoch_ns`."""
        return self._call("epoch_ns", *args)

    def epoch_us(self, *args: object) -> Expr:
        """Extract the epoch component in microseconds from a temporal type. SQL: `epoch_us`."""
        return self._call("epoch_us", *args)

    def era(self, *args: object) -> Expr:
        """Extract the era component from a date or timestamp. SQL: `era`."""
        return self._call("era", *args)

    def hour(self, *args: object) -> Expr:
        """Extract the hour component from a date or timestamp. SQL: `hour`."""
        return self._call("hour", *args)

    def isodow(self, *args: object) -> Expr:
        """Extract the isodow component from a date or timestamp. SQL: `isodow`."""
        return self._call("isodow", *args)

    def isoyear(self, *args: object) -> Expr:
        """Extract the isoyear component from a date or timestamp. SQL: `isoyear`."""
        return self._call("isoyear", *args)

    def julian(self, *args: object) -> Expr:
        """Extract the Julian Day number from a date or timestamp. SQL: `julian`."""
        return self._call("julian", *args)

    def last_day(self, *args: object) -> DtExpr:
        """Returns the last day of the month. SQL: `last_day`."""
        return DtExpr(self._call("last_day", *args))

    def microsecond(self, *args: object) -> Expr:
        """Extract the microsecond component from a date or timestamp. SQL: `microsecond`."""
        return self._call("microsecond", *args)

    def millennium(self, *args: object) -> Expr:
        """Extract the millennium component from a date or timestamp. SQL: `millennium`."""
        return self._call("millennium", *args)

    def millisecond(self, *args: object) -> Expr:
        """Extract the millisecond component from a date or timestamp. SQL: `millisecond`."""
        return self._call("millisecond", *args)

    def minute(self, *args: object) -> Expr:
        """Extract the minute component from a date or timestamp. SQL: `minute`."""
        return self._call("minute", *args)

    def month(self, *args: object) -> Expr:
        """Extract the month component from a date or timestamp. SQL: `month`."""
        return self._call("month", *args)

    def monthname(self, *args: object) -> StrExpr:
        """The (English) name of the month. SQL: `monthname`."""
        return StrExpr(self._call("monthname", *args))

    def nanosecond(self, *args: object) -> Expr:
        """Extract the nanosecond component from a date or timestamp. SQL: `nanosecond`."""
        return self._call("nanosecond", *args)

    def normalized_interval(self, *args: object) -> DtExpr:
        """Normalizes an INTERVAL to an equivalent interval. SQL: `normalized_interval`."""
        return DtExpr(self._call("normalized_interval", *args))

    def part(self, part: object, *args: object) -> Expr:
        """Get subfield (equivalent to extract). Arguments: part. SQL: `date_part`."""
        return self._call_at("date_part", 1, part, *args)

    def quarter(self, *args: object) -> Expr:
        """Extract the quarter component from a date or timestamp. SQL: `quarter`."""
        return self._call("quarter", *args)

    def second(self, *args: object) -> Expr:
        """Extract the second component from a date or timestamp. SQL: `second`."""
        return self._call("second", *args)

    def strftime(self, *args: object) -> StrExpr:
        """Format as text, with a strftime pattern. Arguments: format. SQL: `strftime`."""
        return StrExpr(self._call("strftime", *args))

    def sub(self, part: object, *args: object) -> Expr:
        """The number of complete partitions between the timestamps. Arguments: part, enddate. SQL: `date_sub`."""
        return self._call_at("date_sub", 1, part, *args)

    def time_bucket(self, bucket_width: object, *args: object) -> DtExpr:
        """Truncate TIMESTAMPTZ by the specified interval bucket_width.

        Arguments: bucket_width. SQL: `time_bucket`.
        """
        return DtExpr(self._call_at("time_bucket", 1, bucket_width, *args))

    def timetz_byte_comparable(self, *args: object) -> Expr:
        """Converts a TIME WITH TIME ZONE to an integer sort key. SQL: `timetz_byte_comparable`."""
        return self._call("timetz_byte_comparable", *args)

    def timezone(self, *args: object) -> Expr:
        """The time zone offset, in seconds. SQL: `timezone`."""
        return self._call("timezone", *args)

    def timezone_hour(self, *args: object) -> Expr:
        """Extract the timezone_hour component from a date or timestamp. SQL: `timezone_hour`."""
        return self._call("timezone_hour", *args)

    def timezone_minute(self, *args: object) -> Expr:
        """Extract the timezone_minute component from a date or timestamp. SQL: `timezone_minute`."""
        return self._call("timezone_minute", *args)

    def trunc(self, part: object, *args: object) -> DtExpr:
        """Truncate to specified precision. Arguments: part. SQL: `date_trunc`."""
        return DtExpr(self._call_at("date_trunc", 1, part, *args))

    def week(self, *args: object) -> Expr:
        """Extract the week component from a date or timestamp. SQL: `week`."""
        return self._call("week", *args)

    def weekday(self, *args: object) -> Expr:
        """Extract the weekday component from a date or timestamp. SQL: `weekday`."""
        return self._call("weekday", *args)

    def weekofyear(self, *args: object) -> Expr:
        """Extract the weekofyear component from a date or timestamp. SQL: `weekofyear`."""
        return self._call("weekofyear", *args)

    def year(self, *args: object) -> Expr:
        """Extract the year component from a date or timestamp. SQL: `year`."""
        return self._call("year", *args)

    def yearweek(self, *args: object) -> Expr:
        """Extract the yearweek component from a date or timestamp. SQL: `yearweek`."""
        return self._call("yearweek", *args)


class ListExpr(FamilyExpr):
    """List functions, applied to this expression as the list."""

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "aggregate": ("list_aggregate", 0, ["ANY[]", "VARCHAR"]),
        "any_value": ("list_any_value", 0, []),
        "append": ("list_append", 0, []),
        "approx_count_distinct": ("list_approx_count_distinct", 0, []),
        "avg": ("list_avg", 0, []),
        "bit_and": ("list_bit_and", 0, []),
        "bit_or": ("list_bit_or", 0, []),
        "bit_xor": ("list_bit_xor", 0, []),
        "bool_and": ("list_bool_and", 0, []),
        "bool_or": ("list_bool_or", 0, []),
        "contains": ("list_contains", 0, ["T[]", "T"]),
        "cosine_distance": ("list_cosine_distance", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "cosine_similarity": ("list_cosine_similarity", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "count": ("list_count", 0, []),
        "distance": ("list_distance", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "distinct": ("list_distinct", 0, ["T[]"]),
        "entropy": ("list_entropy", 0, []),
        "extract": ("list_extract", 0, ["T[]", "BIGINT"]),
        "filter": ("list_filter", 0, ["ANY[]", "LAMBDA"]),
        "first": ("list_first", 0, []),
        "flatten": ("flatten", 0, ["T[][]"]),
        "grade_up": ("list_grade_up", 0, ["ANY[]"]),
        "has_all": ("list_has_all", 0, ["T[]", "T[]"]),
        "has_any": ("list_has_any", 0, ["T[]", "T[]"]),
        "histogram": ("list_histogram", 0, []),
        "inner_product": ("list_inner_product", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "intersect": ("list_intersect", 0, ["T[]", "T[]"]),
        "kurtosis": ("list_kurtosis", 0, []),
        "kurtosis_pop": ("list_kurtosis_pop", 0, []),
        "last": ("list_last", 0, []),
        "mad": ("list_mad", 0, []),
        "mask": ("list_where", 0, ["T[]", "BOOLEAN[]"]),
        "max": ("list_max", 0, []),
        "median": ("list_median", 0, []),
        "min": ("list_min", 0, []),
        "mode": ("list_mode", 0, []),
        "negative_inner_product": ("list_negative_inner_product", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "position": ("list_position", 0, ["T[]", "T"]),
        "prepend": ("list_prepend", 1, []),
        "product": ("list_product", 0, []),
        "reduce": ("list_reduce", 0, ["ANY[]", "LAMBDA"]),
        "resize": ("list_resize", 0, ["ANY[]", "ANY"]),
        "reverse": ("list_reverse", 0, []),
        "reverse_sort": ("list_reverse_sort", 0, ["ANY[]"]),
        "select": ("list_select", 0, ["T[]", "BIGINT[]"]),
        "sem": ("list_sem", 0, []),
        "skewness": ("list_skewness", 0, []),
        "sort": ("list_sort", 0, ["ANY[]"]),
        "stddev_pop": ("list_stddev_pop", 0, []),
        "stddev_samp": ("list_stddev_samp", 0, []),
        "string_agg": ("list_string_agg", 0, []),
        "sum": ("list_sum", 0, []),
        "transform": ("list_transform", 0, ["ANY[]", "LAMBDA"]),
        "unique": ("list_unique", 0, ["ANY[]"]),
        "var_pop": ("list_var_pop", 0, []),
        "var_samp": ("list_var_samp", 0, []),
    }

    def aggregate(self, *args: object) -> Expr:
        """Executes the aggregate function `function_name` on the elements of `l...

        Arguments: function_name. SQL: `list_aggregate`.
        """
        return self._call("list_aggregate", *args)

    def any_value(self, *args: object) -> Expr:
        """Any one element, whichever is cheapest. SQL: `list_any_value`."""
        return self._call("list_any_value", *args)

    def append(self, *args: object) -> ListExpr:
        """The `list_append` function. Arguments: e. SQL: `list_append`."""
        return ListExpr(self._call("list_append", *args))

    def approx_count_distinct(self, *args: object) -> Expr:
        """An approximate count of the distinct elements. SQL: `list_approx_count_distinct`."""
        return self._call("list_approx_count_distinct", *args)

    def avg(self, *args: object) -> Expr:
        """The average of the elements. SQL: `list_avg`."""
        return self._call("list_avg", *args)

    def bit_and(self, *args: object) -> Expr:
        """The bitwise AND of the elements. SQL: `list_bit_and`."""
        return self._call("list_bit_and", *args)

    def bit_or(self, *args: object) -> Expr:
        """The bitwise OR of the elements. SQL: `list_bit_or`."""
        return self._call("list_bit_or", *args)

    def bit_xor(self, *args: object) -> Expr:
        """The bitwise XOR of the elements. SQL: `list_bit_xor`."""
        return self._call("list_bit_xor", *args)

    def bool_and(self, *args: object) -> Expr:
        """Whether every element is true. SQL: `list_bool_and`."""
        return self._call("list_bool_and", *args)

    def bool_or(self, *args: object) -> Expr:
        """Whether any element is true. SQL: `list_bool_or`."""
        return self._call("list_bool_or", *args)

    def contains(self, *args: object) -> Expr:
        """Returns true if the list contains the element. Arguments: element. SQL: `list_contains`."""
        return self._call("list_contains", *args)

    def cosine_distance(self, *args: object) -> Expr:
        """Computes the cosine distance between two same-sized lists.

        Arguments: list2. SQL: `list_cosine_distance`.
        """
        return self._call("list_cosine_distance", *args)

    def cosine_similarity(self, *args: object) -> Expr:
        """Computes the cosine similarity between two same-sized lists.

        Arguments: list2. SQL: `list_cosine_similarity`.
        """
        return self._call("list_cosine_similarity", *args)

    def count(self, *args: object) -> Expr:
        """How many elements are not NULL. SQL: `list_count`."""
        return self._call("list_count", *args)

    def distance(self, *args: object) -> Expr:
        """Calculates the Euclidean distance between two points with coordinates...

        Arguments: list2. SQL: `list_distance`.
        """
        return self._call("list_distance", *args)

    def distinct(self, *args: object) -> ListExpr:
        """Removes all duplicates and `NULL` values from a list. SQL: `list_distinct`."""
        return ListExpr(self._call("list_distinct", *args))

    def entropy(self, *args: object) -> Expr:
        """The entropy of the elements. SQL: `list_entropy`."""
        return self._call("list_entropy", *args)

    def extract(self, *args: object) -> Expr:
        """Extract the `index`th (1-based) value from the list. Arguments: index. SQL: `list_extract`."""
        return self._call("list_extract", *args)

    def filter(self, function: object, *args: object) -> ListExpr:
        """The elements the function holds for: `lambda x: x > 0`.

        A Python callable of one argument, run once at build time on
        expressions, not values. SQL: `list_filter`.
        """
        return ListExpr(self._call("list_filter", function, *args))

    def first(self, *args: object) -> Expr:
        """The first element. SQL: `list_first`."""
        return self._call("list_first", *args)

    def flatten(self, *args: object) -> ListExpr:
        """Flattens a nested list by one level. SQL: `flatten`."""
        return ListExpr(self._call("flatten", *args))

    def grade_up(self, *args: object) -> ListExpr:
        """Works like list_sort, but the results are the indexes that correspond... SQL: `list_grade_up`."""
        return ListExpr(self._call("list_grade_up", *args))

    def has_all(self, *args: object) -> Expr:
        """Returns true if all elements of list2 are in list1. Arguments: list2. SQL: `list_has_all`."""
        return self._call("list_has_all", *args)

    def has_any(self, *args: object) -> Expr:
        """Returns true if the lists have any element in common. Arguments: list2. SQL: `list_has_any`."""
        return self._call("list_has_any", *args)

    def histogram(self, *args: object) -> Expr:
        """How often each element occurs, as a map. SQL: `list_histogram`."""
        return self._call("list_histogram", *args)

    def inner_product(self, *args: object) -> Expr:
        """Computes the inner product between two same-sized lists. Arguments: list2. SQL: `list_inner_product`."""
        return self._call("list_inner_product", *args)

    def intersect(self, *args: object) -> ListExpr:
        """Returns a list containing the distinct elements that are present in b...

        Arguments: list2. SQL: `list_intersect`.
        """
        return ListExpr(self._call("list_intersect", *args))

    def kurtosis(self, *args: object) -> Expr:
        """The kurtosis of the elements. SQL: `list_kurtosis`."""
        return self._call("list_kurtosis", *args)

    def kurtosis_pop(self, *args: object) -> Expr:
        """The population kurtosis of the elements. SQL: `list_kurtosis_pop`."""
        return self._call("list_kurtosis_pop", *args)

    def last(self, *args: object) -> Expr:
        """The last element. SQL: `list_last`."""
        return self._call("list_last", *args)

    def mad(self, *args: object) -> Expr:
        """The median absolute deviation of the elements. SQL: `list_mad`."""
        return self._call("list_mad", *args)

    def mask(self, *args: object) -> ListExpr:
        """The elements where the matching boolean is true. Arguments: mask_list. SQL: `list_where`."""
        return ListExpr(self._call("list_where", *args))

    def max(self, *args: object) -> Expr:
        """The largest element. SQL: `list_max`."""
        return self._call("list_max", *args)

    def median(self, *args: object) -> Expr:
        """The middle element. SQL: `list_median`."""
        return self._call("list_median", *args)

    def min(self, *args: object) -> Expr:
        """The smallest element. SQL: `list_min`."""
        return self._call("list_min", *args)

    def mode(self, *args: object) -> Expr:
        """The most frequent element. SQL: `list_mode`."""
        return self._call("list_mode", *args)

    def negative_inner_product(self, *args: object) -> Expr:
        """Computes the negative inner product between two same-sized lists.

        Arguments: list2. SQL: `list_negative_inner_product`.
        """
        return self._call("list_negative_inner_product", *args)

    def position(self, *args: object) -> Expr:
        """Returns the index of the `element` if the `list` contains the `element`.

        Arguments: element. SQL: `list_position`.
        """
        return self._call("list_position", *args)

    def prepend(self, e: object, *args: object) -> ListExpr:
        """The `list_prepend` function. Arguments: e. SQL: `list_prepend`."""
        return ListExpr(self._call_at("list_prepend", 1, e, *args))

    def product(self, *args: object) -> Expr:
        """The product of the elements. SQL: `list_product`."""
        return self._call("list_product", *args)

    def reduce(self, function: object, *args: object) -> Expr:
        """The list folded to one value, left to right: `lambda acc, x: acc + x`.

        A Python callable of two arguments, run once at build time on
        expressions, not values. SQL: `list_reduce`.
        """
        return self._call("list_reduce", function, *args)

    def resize(self, *args: object) -> ListExpr:
        """Resizes the `list` to contain `size` elements. Arguments: size. SQL: `list_resize`."""
        return ListExpr(self._call("list_resize", *args))

    def reverse(self, *args: object) -> ListExpr:
        """The elements in reverse order. SQL: `list_reverse`."""
        return ListExpr(self._call("list_reverse", *args))

    def reverse_sort(self, *args: object) -> ListExpr:
        """Sorts the elements of the list in reverse order. SQL: `list_reverse_sort`."""
        return ListExpr(self._call("list_reverse_sort", *args))

    def select(self, *args: object) -> ListExpr:
        """Returns a list based on the elements selected by the `index_list`.

        Arguments: index_list. SQL: `list_select`.
        """
        return ListExpr(self._call("list_select", *args))

    def sem(self, *args: object) -> Expr:
        """The standard error of the mean of the elements. SQL: `list_sem`."""
        return self._call("list_sem", *args)

    def skewness(self, *args: object) -> Expr:
        """The skewness of the elements. SQL: `list_skewness`."""
        return self._call("list_skewness", *args)

    def sort(self, *args: object) -> ListExpr:
        """Sorts the elements of the list. SQL: `list_sort`."""
        return ListExpr(self._call("list_sort", *args))

    def stddev_pop(self, *args: object) -> Expr:
        """The population standard deviation of the elements. SQL: `list_stddev_pop`."""
        return self._call("list_stddev_pop", *args)

    def stddev_samp(self, *args: object) -> Expr:
        """The sample standard deviation of the elements. SQL: `list_stddev_samp`."""
        return self._call("list_stddev_samp", *args)

    def string_agg(self, *args: object) -> StrExpr:
        """The elements joined as text, separated by commas. SQL: `list_string_agg`."""
        return StrExpr(self._call("list_string_agg", *args))

    def sum(self, *args: object) -> Expr:
        """The sum of the elements. SQL: `list_sum`."""
        return self._call("list_sum", *args)

    def transform(self, function: object, *args: object) -> ListExpr:
        """Each element through the function: `lambda x: x * 2`.

        A Python callable of one argument, run once at build time on
        expressions, not values. SQL: `list_transform`.
        """
        return ListExpr(self._call("list_transform", function, *args))

    def unique(self, *args: object) -> Expr:
        """Counts the unique elements of a `list`. SQL: `list_unique`."""
        return self._call("list_unique", *args)

    def var_pop(self, *args: object) -> Expr:
        """The population variance of the elements. SQL: `list_var_pop`."""
        return self._call("list_var_pop", *args)

    def var_samp(self, *args: object) -> Expr:
        """The sample variance of the elements. SQL: `list_var_samp`."""
        return self._call("list_var_samp", *args)


class JsonExpr(StrExpr):
    """JSON functions, applied to this expression as the document."""

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "array_length": ("json_array_length", 0, ["JSON"]),
        "contains": ("json_contains", 0, ["JSON", "JSON"]),
        "deep_merge": ("json_deep_merge", 0, ["JSON", "JSON"]),
        "exists": ("json_exists", 0, ["JSON", "VARCHAR"]),
        "extract": ("json_extract", 0, ["JSON", "VARCHAR"]),
        "extract_path": ("json_extract_path", 0, ["JSON", "VARCHAR"]),
        "extract_path_text": ("json_extract_path_text", 0, ["JSON", "VARCHAR"]),
        "extract_string": ("json_extract_string", 0, ["JSON", "VARCHAR"]),
        "insert": ("json_insert", 0, ["JSON", "VARCHAR", "JSON"]),
        "keys": ("json_keys", 0, ["JSON"]),
        "merge_patch_diff": ("json_merge_patch_diff", 0, ["JSON", "JSON"]),
        "normalize": ("json_normalize", 0, ["JSON"]),
        "parse": ("json", 0, []),
        "pretty": ("json_pretty", 0, ["JSON"]),
        "remove": ("json_remove", 0, ["JSON", "VARCHAR"]),
        "replace": ("json_replace", 0, ["JSON", "VARCHAR", "JSON"]),
        "set": ("json_set", 0, ["JSON", "VARCHAR", "JSON"]),
        "strip_nulls": ("json_strip_nulls", 0, ["JSON"]),
        "structure": ("json_structure", 0, ["JSON"]),
        "transform": ("json_transform", 0, ["JSON", "VARCHAR"]),
        "transform_strict": ("json_transform_strict", 0, ["JSON", "VARCHAR"]),
        "type": ("json_type", 0, ["JSON"]),
        "valid": ("json_valid", 0, ["JSON"]),
        "value": ("json_value", 0, ["JSON", "VARCHAR"]),
    }

    def array_length(self, *args: object) -> Expr:
        """How many elements the array holds. SQL: `json_array_length`."""
        return self._call("json_array_length", *args)

    def contains(self, *args: object) -> Expr:
        """The `json_contains` function. Arguments: col1. SQL: `json_contains`."""
        return self._call("json_contains", *args)

    def deep_merge(self, *args: object) -> JsonExpr:
        """The `json_deep_merge` function. Arguments: col1. SQL: `json_deep_merge`."""
        return JsonExpr(self._call("json_deep_merge", *args))

    def exists(self, *args: object) -> Expr:
        """The `json_exists` function. Arguments: col1. SQL: `json_exists`."""
        return self._call("json_exists", *args)

    def extract(self, *args: object) -> JsonExpr:
        """The `json_extract` function. Arguments: col1. SQL: `json_extract`."""
        return JsonExpr(self._call("json_extract", *args))

    def extract_path(self, *args: object) -> JsonExpr:
        """The `json_extract_path` function. Arguments: col1. SQL: `json_extract_path`."""
        return JsonExpr(self._call("json_extract_path", *args))

    def extract_path_text(self, *args: object) -> StrExpr:
        """The `json_extract_path_text` function. Arguments: col1. SQL: `json_extract_path_text`."""
        return StrExpr(self._call("json_extract_path_text", *args))

    def extract_string(self, *args: object) -> StrExpr:
        """The `json_extract_string` function. Arguments: col1. SQL: `json_extract_string`."""
        return StrExpr(self._call("json_extract_string", *args))

    def insert(self, *args: object) -> JsonExpr:
        """The `json_insert` function. Arguments: col1, col2. SQL: `json_insert`."""
        return JsonExpr(self._call("json_insert", *args))

    def keys(self, *args: object) -> ListExpr:
        """The keys of the object, as a list. SQL: `json_keys`."""
        return ListExpr(self._call("json_keys", *args))

    def merge_patch_diff(self, *args: object) -> JsonExpr:
        """The `json_merge_patch_diff` function. Arguments: col1. SQL: `json_merge_patch_diff`."""
        return JsonExpr(self._call("json_merge_patch_diff", *args))

    def normalize(self, *args: object) -> StrExpr:
        """The document minified, with object keys sorted. SQL: `json_normalize`."""
        return StrExpr(self._call("json_normalize", *args))

    def parse(self, *args: object) -> JsonExpr:
        """The text parsed as a JSON document, minified. SQL: `json`."""
        return JsonExpr(self._call("json", *args))

    def pretty(self, *args: object) -> StrExpr:
        """The document printed with indentation. SQL: `json_pretty`."""
        return StrExpr(self._call("json_pretty", *args))

    def remove(self, *args: object) -> JsonExpr:
        """The `json_remove` function. Arguments: col1. SQL: `json_remove`."""
        return JsonExpr(self._call("json_remove", *args))

    def replace(self, *args: object) -> JsonExpr:
        """The `json_replace` function. Arguments: col1, col2. SQL: `json_replace`."""
        return JsonExpr(self._call("json_replace", *args))

    def set(self, *args: object) -> JsonExpr:
        """The `json_set` function. Arguments: col1, col2. SQL: `json_set`."""
        return JsonExpr(self._call("json_set", *args))

    def strip_nulls(self, *args: object) -> JsonExpr:
        """The document without its null-valued object fields. SQL: `json_strip_nulls`."""
        return JsonExpr(self._call("json_strip_nulls", *args))

    def structure(self, *args: object) -> JsonExpr:
        """The shape of the document, with types in place of values. SQL: `json_structure`."""
        return JsonExpr(self._call("json_structure", *args))

    def transform(self, *args: object) -> Expr:
        """The `json_transform` function. Arguments: structure. SQL: `json_transform`."""
        return self._call("json_transform", *args)

    def transform_strict(self, *args: object) -> Expr:
        """The `json_transform_strict` function. Arguments: col1. SQL: `json_transform_strict`."""
        return self._call("json_transform_strict", *args)

    def type(self, *args: object) -> StrExpr:
        """The type of the top value: OBJECT, ARRAY, VARCHAR and so on. SQL: `json_type`."""
        return StrExpr(self._call("json_type", *args))

    def valid(self, *args: object) -> Expr:
        """Whether the text is valid JSON. SQL: `json_valid`."""
        return self._call("json_valid", *args)

    def value(self, *args: object) -> StrExpr:
        """The `json_value` function. Arguments: col1. SQL: `json_value`."""
        return StrExpr(self._call("json_value", *args))
