"""The `.str`, `.dt` and `.list` methods on Expr, one per engine function.

Generated by scripts/gen_namespaces.py from duckdb_functions(). Do not edit;
regenerate after bumping engine.pin.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class _Namespace:
    """A group of functions applied to one expression."""

    __slots__ = ("_expr",)

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {}

    def __init__(self, expr: Expr) -> None:
        self._expr = expr


class StringMethods(_Namespace):
    """Text functions, applied to this expression as the string."""

    __slots__ = ()

    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "ascii": ("ascii", 0, ["VARCHAR"]),
        "bin": ("bin", 0, ["VARCHAR"]),
        "bit_length": ("bit_length", 0, ["VARCHAR"]),
        "concat_ws": ("concat_ws", 0, ["VARCHAR", "ANY"]),
        "contains": ("contains", 0, ["VARCHAR", "VARCHAR"]),
        "damerau_levenshtein": ("damerau_levenshtein", 0, ["VARCHAR", "VARCHAR"]),
        "format": ("format", 0, ["VARCHAR"]),
        "from_base64": ("from_base64", 0, ["VARCHAR"]),
        "hamming": ("hamming", 0, ["VARCHAR", "VARCHAR"]),
        "ilike_escape": ("ilike_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "instr": ("instr", 0, ["VARCHAR", "VARCHAR"]),
        "jaccard": ("jaccard", 0, ["VARCHAR", "VARCHAR"]),
        "jaro_similarity": ("jaro_similarity", 0, ["VARCHAR", "VARCHAR"]),
        "jaro_winkler_similarity": ("jaro_winkler_similarity", 0, ["VARCHAR", "VARCHAR"]),
        "left": ("left", 0, ["VARCHAR", "BIGINT"]),
        "left_grapheme": ("left_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "length": ("length", 0, ["VARCHAR"]),
        "length_grapheme": ("length_grapheme", 0, ["VARCHAR"]),
        "levenshtein": ("levenshtein", 0, ["VARCHAR", "VARCHAR"]),
        "like_escape": ("like_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "lower": ("lower", 0, ["VARCHAR"]),
        "lpad": ("lpad", 0, ["VARCHAR", "INTEGER", "VARCHAR"]),
        "ltrim": ("ltrim", 0, ["VARCHAR"]),
        "md5": ("md5", 0, ["VARCHAR"]),
        "md5_number": ("md5_number", 0, ["VARCHAR"]),
        "nfc_normalize": ("nfc_normalize", 0, ["VARCHAR"]),
        "not_ilike_escape": ("not_ilike_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "not_like_escape": ("not_like_escape", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "overlay": ("overlay", 0, ["VARCHAR", "VARCHAR", "BIGINT"]),
        "parse_dirname": ("parse_dirname", 0, ["VARCHAR"]),
        "parse_dirpath": ("parse_dirpath", 0, ["VARCHAR"]),
        "parse_filename": ("parse_filename", 0, ["VARCHAR"]),
        "parse_formatted_bytes": ("parse_formatted_bytes", 0, ["VARCHAR"]),
        "parse_path": ("parse_path", 0, ["VARCHAR"]),
        "path_join": ("path_join", 0, ["VARCHAR"]),
        "prefix": ("prefix", 0, ["VARCHAR", "VARCHAR"]),
        "printf": ("printf", 0, ["VARCHAR"]),
        "regexp_escape": ("regexp_escape", 0, ["VARCHAR"]),
        "regexp_extract": ("regexp_extract", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_extract_all": ("regexp_extract_all", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_full_match": ("regexp_full_match", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_matches": ("regexp_matches", 0, ["VARCHAR", "VARCHAR"]),
        "regexp_replace": ("regexp_replace", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "replace": ("replace", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "reverse": ("reverse", 0, ["VARCHAR"]),
        "right": ("right", 0, ["VARCHAR", "BIGINT"]),
        "right_grapheme": ("right_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "rpad": ("rpad", 0, ["VARCHAR", "INTEGER", "VARCHAR"]),
        "rtrim": ("rtrim", 0, ["VARCHAR"]),
        "sha1": ("sha1", 0, ["VARCHAR"]),
        "sha256": ("sha256", 0, ["VARCHAR"]),
        "string_split": ("string_split", 0, ["VARCHAR", "VARCHAR"]),
        "string_split_regex": ("string_split_regex", 0, ["VARCHAR", "VARCHAR"]),
        "strip_accents": ("strip_accents", 0, ["VARCHAR"]),
        "strlen": ("strlen", 0, ["VARCHAR"]),
        "substring": ("substring", 0, ["VARCHAR", "BIGINT"]),
        "substring_grapheme": ("substring_grapheme", 0, ["VARCHAR", "BIGINT"]),
        "suffix": ("suffix", 0, ["VARCHAR", "VARCHAR"]),
        "translate": ("translate", 0, ["VARCHAR", "VARCHAR", "VARCHAR"]),
        "trim": ("trim", 0, ["VARCHAR"]),
        "unbin": ("unbin", 0, ["VARCHAR"]),
        "unhex": ("unhex", 0, ["VARCHAR"]),
        "unicode": ("unicode", 0, ["VARCHAR"]),
        "upper": ("upper", 0, ["VARCHAR"]),
        "url_decode": ("url_decode", 0, ["VARCHAR"]),
        "url_encode": ("url_encode", 0, ["VARCHAR"]),
    }

    def ascii(self) -> Expr:
        """Returns an integer that represents the Unicode code point of the firs. SQL: `ascii`."""
        return self._expr._call("ascii")

    def bin(self) -> Expr:
        """Converts the `string` to binary representation. SQL: `bin`."""
        return self._expr._call("bin")

    def bit_length(self) -> Expr:
        """Number of bits in a `string`. SQL: `bit_length`."""
        return self._expr._call("bit_length")

    def concat_ws(self, *args: object) -> Expr:
        """Concatenates many strings, separated by `separator`. Arguments: string. SQL: `concat_ws`."""
        return self._expr._call("concat_ws", *args)

    def contains(self, *args: object) -> Expr:
        """Returns `true` if `search_string` is found within `string`. Arguments: search_string. SQL: `contains`."""
        return self._expr._call("contains", *args)

    def damerau_levenshtein(self, *args: object) -> Expr:
        """Extension of Levenshtein distance to also include transposition of ad.

        Arguments: s2. SQL: `damerau_levenshtein`.
        """
        return self._expr._call("damerau_levenshtein", *args)

    def format(self) -> Expr:
        """Formats a string using the fmt syntax. SQL: `format`."""
        return self._expr._call("format")

    def from_base64(self) -> Expr:
        """Converts a base64 encoded `string` to a character string (`BLOB`). SQL: `from_base64`."""
        return self._expr._call("from_base64")

    def hamming(self, *args: object) -> Expr:
        """The Hamming distance between to strings, i.e., the number of position. Arguments: s2. SQL: `hamming`."""
        return self._expr._call("hamming", *args)

    def ilike_escape(self, *args: object) -> Expr:
        """Returns `true` if the `string` matches the `like_specifier` (see Patt.

        Arguments: like_specifier, escape_character. SQL: `ilike_escape`.
        """
        return self._expr._call("ilike_escape", *args)

    def instr(self, *args: object) -> Expr:
        """Returns location of first occurrence of `search_string` in `string`,.

        Arguments: search_string. SQL: `instr`.
        """
        return self._expr._call("instr", *args)

    def jaccard(self, *args: object) -> Expr:
        """The Jaccard similarity between two strings. Arguments: s2. SQL: `jaccard`."""
        return self._expr._call("jaccard", *args)

    def jaro_similarity(self, *args: object) -> Expr:
        """The Jaro similarity between two strings. Arguments: s2. SQL: `jaro_similarity`."""
        return self._expr._call("jaro_similarity", *args)

    def jaro_winkler_similarity(self, *args: object) -> Expr:
        """The Jaro-Winkler similarity between two strings. Arguments: s2. SQL: `jaro_winkler_similarity`."""
        return self._expr._call("jaro_winkler_similarity", *args)

    def left(self, *args: object) -> Expr:
        """Extracts the left-most count characters. Arguments: count. SQL: `left`."""
        return self._expr._call("left", *args)

    def left_grapheme(self, *args: object) -> Expr:
        """Extracts the left-most count grapheme clusters. Arguments: count. SQL: `left_grapheme`."""
        return self._expr._call("left_grapheme", *args)

    def length(self) -> Expr:
        """Number of characters in `string`. SQL: `length`."""
        return self._expr._call("length")

    def length_grapheme(self) -> Expr:
        """Number of grapheme clusters in `string`. SQL: `length_grapheme`."""
        return self._expr._call("length_grapheme")

    def levenshtein(self, *args: object) -> Expr:
        """The minimum number of single-character edits (insertions, deletions o.

        Arguments: s2. SQL: `levenshtein`.
        """
        return self._expr._call("levenshtein", *args)

    def like_escape(self, *args: object) -> Expr:
        """Returns `true` if the `string` matches the `like_specifier` (see Patt.

        Arguments: like_specifier, escape_character. SQL: `like_escape`.
        """
        return self._expr._call("like_escape", *args)

    def lower(self) -> Expr:
        """Converts `string` to lower case. SQL: `lower`."""
        return self._expr._call("lower")

    def lpad(self, *args: object) -> Expr:
        """Pads the `string` with the `character` on the left until it has `coun.

        Arguments: count, character. SQL: `lpad`.
        """
        return self._expr._call("lpad", *args)

    def ltrim(self) -> Expr:
        """Removes any occurrences of any of the `characters` from the left side. SQL: `ltrim`."""
        return self._expr._call("ltrim")

    def md5(self) -> Expr:
        """Returns the MD5 hash of the `string` as a `VARCHAR`. SQL: `md5`."""
        return self._expr._call("md5")

    def md5_number(self) -> Expr:
        """Returns the MD5 hash of the `string` as a `HUGEINT`. SQL: `md5_number`."""
        return self._expr._call("md5_number")

    def nfc_normalize(self) -> Expr:
        """Converts `string` to Unicode NFC normalized string. SQL: `nfc_normalize`."""
        return self._expr._call("nfc_normalize")

    def not_ilike_escape(self, *args: object) -> Expr:
        """Returns `false` if the `string` matches the `like_specifier` (see Pat.

        Arguments: like_specifier, escape_character. SQL: `not_ilike_escape`.
        """
        return self._expr._call("not_ilike_escape", *args)

    def not_like_escape(self, *args: object) -> Expr:
        """Returns `false` if the `string` matches the `like_specifier` (see Pat.

        Arguments: like_specifier, escape_character. SQL: `not_like_escape`.
        """
        return self._expr._call("not_like_escape", *args)

    def overlay(self, *args: object) -> Expr:
        """Replaces a substring of `string` starting at character `start` with `.

        Arguments: replacement, start. SQL: `overlay`.
        """
        return self._expr._call("overlay", *args)

    def parse_dirname(self) -> Expr:
        """Returns the top-level directory name from the given `path`. SQL: `parse_dirname`."""
        return self._expr._call("parse_dirname")

    def parse_dirpath(self) -> Expr:
        """Returns the head of the `path` (the pathname until the last slash) si. SQL: `parse_dirpath`."""
        return self._expr._call("parse_dirpath")

    def parse_filename(self) -> Expr:
        """Returns the last component of the `path` similarly to Python's `os.pa. SQL: `parse_filename`."""
        return self._expr._call("parse_filename")

    def parse_formatted_bytes(self) -> Expr:
        """Parses a human-readable representation of a size in bytes into an int. SQL: `parse_formatted_bytes`."""
        return self._expr._call("parse_formatted_bytes")

    def parse_path(self) -> Expr:
        """Returns a list of the components (directories and filename) in the `p. SQL: `parse_path`."""
        return self._expr._call("parse_path")

    def path_join(self) -> Expr:
        """Joins path components using the platform separator, normalizing dupli. SQL: `path_join`."""
        return self._expr._call("path_join")

    def prefix(self, *args: object) -> Expr:
        """Returns `true` if `string` starts with `search_string`. Arguments: search_string. SQL: `prefix`."""
        return self._expr._call("prefix", *args)

    def printf(self) -> Expr:
        """Formats a `string` using printf syntax. SQL: `printf`."""
        return self._expr._call("printf")

    def regexp_escape(self) -> Expr:
        """Escapes special patterns to turn `string` into a regular expression s. SQL: `regexp_escape`."""
        return self._expr._call("regexp_escape")

    def regexp_extract(self, *args: object) -> Expr:
        """If `string` contains the `regex` pattern, returns the capturing group.

        Arguments: regex. SQL: `regexp_extract`.
        """
        return self._expr._call("regexp_extract", *args)

    def regexp_extract_all(self, *args: object) -> Expr:
        """Finds non-overlapping occurrences of the `regex` in the `string` and.

        Arguments: regex. SQL: `regexp_extract_all`.
        """
        return self._expr._call("regexp_extract_all", *args)

    def regexp_full_match(self, *args: object) -> Expr:
        """Returns `true` if the entire `string` matches the `regex`. Arguments: regex. SQL: `regexp_full_match`."""
        return self._expr._call("regexp_full_match", *args)

    def regexp_matches(self, *args: object) -> Expr:
        """Returns `true` if `string` contains the `regex`, `false` otherwise.

        Arguments: regex. SQL: `regexp_matches`.
        """
        return self._expr._call("regexp_matches", *args)

    def regexp_replace(self, *args: object) -> Expr:
        """If `string` contains the `regex`, replaces the matching part with `re.

        Arguments: regex, replacement. SQL: `regexp_replace`.
        """
        return self._expr._call("regexp_replace", *args)

    def replace(self, *args: object) -> Expr:
        """Replaces any occurrences of the `source` with `target` in `string`.

        Arguments: source, target. SQL: `replace`.
        """
        return self._expr._call("replace", *args)

    def reverse(self) -> Expr:
        """Reverses the `string`. SQL: `reverse`."""
        return self._expr._call("reverse")

    def right(self, *args: object) -> Expr:
        """Extract the right-most `count` characters. Arguments: count. SQL: `right`."""
        return self._expr._call("right", *args)

    def right_grapheme(self, *args: object) -> Expr:
        """Extracts the right-most `count` grapheme clusters. Arguments: count. SQL: `right_grapheme`."""
        return self._expr._call("right_grapheme", *args)

    def rpad(self, *args: object) -> Expr:
        """Pads the `string` with the `character` on the right until it has `cou.

        Arguments: count, character. SQL: `rpad`.
        """
        return self._expr._call("rpad", *args)

    def rtrim(self) -> Expr:
        """Removes any occurrences of any of the `characters` from the right sid. SQL: `rtrim`."""
        return self._expr._call("rtrim")

    def sha1(self) -> Expr:
        """Returns a `VARCHAR` with the SHA-1 hash of the `value`. SQL: `sha1`."""
        return self._expr._call("sha1")

    def sha256(self) -> Expr:
        """Returns a `VARCHAR` with the SHA-256 hash of the `value`. SQL: `sha256`."""
        return self._expr._call("sha256")

    def string_split(self, *args: object) -> Expr:
        """Splits the `string` along the `separator`. Arguments: separator. SQL: `string_split`."""
        return self._expr._call("string_split", *args)

    def string_split_regex(self, *args: object) -> Expr:
        """Splits the `string` along the `regex`. Arguments: regex. SQL: `string_split_regex`."""
        return self._expr._call("string_split_regex", *args)

    def strip_accents(self) -> Expr:
        """Strips accents from `string`. SQL: `strip_accents`."""
        return self._expr._call("strip_accents")

    def strlen(self) -> Expr:
        """Number of bytes in `string`. SQL: `strlen`."""
        return self._expr._call("strlen")

    def substring(self, *args: object) -> Expr:
        """Extracts substring starting from character `start` up to the end of t.

        Arguments: start. SQL: `substring`.
        """
        return self._expr._call("substring", *args)

    def substring_grapheme(self, *args: object) -> Expr:
        """Extracts substring starting from grapheme clusters `start` up to the.

        Arguments: start. SQL: `substring_grapheme`.
        """
        return self._expr._call("substring_grapheme", *args)

    def suffix(self, *args: object) -> Expr:
        """Returns `true` if `string` ends with `search_string`. Arguments: search_string. SQL: `suffix`."""
        return self._expr._call("suffix", *args)

    def translate(self, *args: object) -> Expr:
        """Replaces each character in `string` that matches a character in the `.

        Arguments: from, to. SQL: `translate`.
        """
        return self._expr._call("translate", *args)

    def trim(self) -> Expr:
        """Removes any occurrences of any of the `characters` from either side o. SQL: `trim`."""
        return self._expr._call("trim")

    def unbin(self) -> Expr:
        """Converts a `value` from binary representation to a blob. SQL: `unbin`."""
        return self._expr._call("unbin")

    def unhex(self) -> Expr:
        """Converts a `value` from hexadecimal representation to a blob. SQL: `unhex`."""
        return self._expr._call("unhex")

    def unicode(self) -> Expr:
        """Returns an `INTEGER` representing the `unicode` codepoint of the firs. SQL: `unicode`."""
        return self._expr._call("unicode")

    def upper(self) -> Expr:
        """Converts `string` to upper case. SQL: `upper`."""
        return self._expr._call("upper")

    def url_decode(self) -> Expr:
        """Decodes a URL from a representation using Percent-Encoding. SQL: `url_decode`."""
        return self._expr._call("url_decode")

    def url_encode(self) -> Expr:
        """Encodes a URL to a representation using Percent-Encoding. SQL: `url_encode`."""
        return self._expr._call("url_encode")


class DateMethods(_Namespace):
    """Date and time functions, applied to this expression as the date, time or timestamp."""

    __slots__ = ()

    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "age": ("age", 0, ["TIMESTAMP"]),
        "century": ("century", 0, ["DATE"]),
        "day": ("day", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "dayname": ("dayname", 0, ["DATE"]),
        "dayofmonth": ("dayofmonth", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "dayofweek": ("dayofweek", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "dayofyear": ("dayofyear", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "decade": ("decade", 0, ["INTERVAL"]),
        "diff": ("date_diff", 1, ["VARCHAR", "TIMESTAMPTZ_NS", "TIMESTAMPTZ_NS"]),
        "epoch": ("epoch", 0, ["TIME WITH TIME ZONE"]),
        "epoch_ns": ("epoch_ns", 0, ["DATE"]),
        "epoch_us": ("epoch_us", 0, ["TIME_NS"]),
        "era": ("era", 0, ["DATE"]),
        "hour": ("hour", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "isodow": ("isodow", 0, ["DATE"]),
        "isoyear": ("isoyear", 0, ["INTERVAL"]),
        "julian": ("julian", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "last_day": ("last_day", 0, ["TIMESTAMP"]),
        "microsecond": ("microsecond", 0, ["TIME"]),
        "millennium": ("millennium", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "millisecond": ("millisecond", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "minute": ("minute", 0, ["TIMESTAMP"]),
        "month": ("month", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "monthname": ("monthname", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "nanosecond": ("nanosecond", 0, ["DATE"]),
        "normalized_interval": ("normalized_interval", 0, ["INTERVAL"]),
        "quarter": ("quarter", 0, ["DATE"]),
        "second": ("second", 0, ["INTERVAL"]),
        "strftime": ("strftime", 0, ["DATE", "VARCHAR"]),
        "sub": ("date_sub", 1, ["VARCHAR", "TIMESTAMP", "TIMESTAMP"]),
        "time_bucket": ("time_bucket", 1, ["INTERVAL", "TIMESTAMP"]),
        "timetz_byte_comparable": ("timetz_byte_comparable", 0, ["TIME WITH TIME ZONE"]),
        "timezone": ("timezone", 0, ["TIME WITH TIME ZONE"]),
        "timezone_hour": ("timezone_hour", 0, ["TIMESTAMP WITH TIME ZONE"]),
        "timezone_minute": ("timezone_minute", 0, ["TIME"]),
        "trunc": ("date_trunc", 1, ["VARCHAR", "TIMESTAMP"]),
        "week": ("week", 0, ["DATE"]),
        "weekday": ("weekday", 0, ["DATE"]),
        "weekofyear": ("weekofyear", 0, ["DATE"]),
        "year": ("year", 0, ["INTERVAL"]),
        "yearweek": ("yearweek", 0, ["DATE"]),
    }

    def age(self) -> Expr:
        """Subtract arguments, resulting in the time difference between the two. SQL: `age`."""
        return self._expr._call("age")

    def century(self) -> Expr:
        """Extract the century component from a date or timestamp. SQL: `century`."""
        return self._expr._call("century")

    def day(self) -> Expr:
        """Extract the day component from a date or timestamp. SQL: `day`."""
        return self._expr._call("day")

    def dayname(self) -> Expr:
        """The (English) name of the weekday. SQL: `dayname`."""
        return self._expr._call("dayname")

    def dayofmonth(self) -> Expr:
        """Extract the dayofmonth component from a date or timestamp. SQL: `dayofmonth`."""
        return self._expr._call("dayofmonth")

    def dayofweek(self) -> Expr:
        """Extract the dayofweek component from a date or timestamp. SQL: `dayofweek`."""
        return self._expr._call("dayofweek")

    def dayofyear(self) -> Expr:
        """Extract the dayofyear component from a date or timestamp. SQL: `dayofyear`."""
        return self._expr._call("dayofyear")

    def decade(self) -> Expr:
        """Extract the decade component from a date or timestamp. SQL: `decade`."""
        return self._expr._call("decade")

    def diff(self, part: object, *args: object) -> Expr:
        """The number of partition boundaries between the timestamps. Arguments: part, enddate. SQL: `date_diff`."""
        return self._expr._call_at("date_diff", 1, part, *args)

    def epoch(self) -> Expr:
        """Extract the epoch component from a temporal type. SQL: `epoch`."""
        return self._expr._call("epoch")

    def epoch_ns(self) -> Expr:
        """Extract the epoch component in nanoseconds from a temporal type. SQL: `epoch_ns`."""
        return self._expr._call("epoch_ns")

    def epoch_us(self) -> Expr:
        """Extract the epoch component in microseconds from a temporal type. SQL: `epoch_us`."""
        return self._expr._call("epoch_us")

    def era(self) -> Expr:
        """Extract the era component from a date or timestamp. SQL: `era`."""
        return self._expr._call("era")

    def hour(self) -> Expr:
        """Extract the hour component from a date or timestamp. SQL: `hour`."""
        return self._expr._call("hour")

    def isodow(self) -> Expr:
        """Extract the isodow component from a date or timestamp. SQL: `isodow`."""
        return self._expr._call("isodow")

    def isoyear(self) -> Expr:
        """Extract the isoyear component from a date or timestamp. SQL: `isoyear`."""
        return self._expr._call("isoyear")

    def julian(self) -> Expr:
        """Extract the Julian Day number from a date or timestamp. SQL: `julian`."""
        return self._expr._call("julian")

    def last_day(self) -> Expr:
        """Returns the last day of the month. SQL: `last_day`."""
        return self._expr._call("last_day")

    def microsecond(self) -> Expr:
        """Extract the microsecond component from a date or timestamp. SQL: `microsecond`."""
        return self._expr._call("microsecond")

    def millennium(self) -> Expr:
        """Extract the millennium component from a date or timestamp. SQL: `millennium`."""
        return self._expr._call("millennium")

    def millisecond(self) -> Expr:
        """Extract the millisecond component from a date or timestamp. SQL: `millisecond`."""
        return self._expr._call("millisecond")

    def minute(self) -> Expr:
        """Extract the minute component from a date or timestamp. SQL: `minute`."""
        return self._expr._call("minute")

    def month(self) -> Expr:
        """Extract the month component from a date or timestamp. SQL: `month`."""
        return self._expr._call("month")

    def monthname(self) -> Expr:
        """The (English) name of the month. SQL: `monthname`."""
        return self._expr._call("monthname")

    def nanosecond(self) -> Expr:
        """Extract the nanosecond component from a date or timestamp. SQL: `nanosecond`."""
        return self._expr._call("nanosecond")

    def normalized_interval(self) -> Expr:
        """Normalizes an INTERVAL to an equivalent interval. SQL: `normalized_interval`."""
        return self._expr._call("normalized_interval")

    def quarter(self) -> Expr:
        """Extract the quarter component from a date or timestamp. SQL: `quarter`."""
        return self._expr._call("quarter")

    def second(self) -> Expr:
        """Extract the second component from a date or timestamp. SQL: `second`."""
        return self._expr._call("second")

    def strftime(self, *args: object) -> Expr:
        """Format as text, with a strftime pattern. Arguments: format. SQL: `strftime`."""
        return self._expr._call("strftime", *args)

    def sub(self, part: object, *args: object) -> Expr:
        """The number of complete partitions between the timestamps. Arguments: part, enddate. SQL: `date_sub`."""
        return self._expr._call_at("date_sub", 1, part, *args)

    def time_bucket(self, bucket_width: object, *args: object) -> Expr:
        """Truncate TIMESTAMPTZ by the specified interval bucket_width.

        Arguments: bucket_width. SQL: `time_bucket`.
        """
        return self._expr._call_at("time_bucket", 1, bucket_width, *args)

    def timetz_byte_comparable(self) -> Expr:
        """Converts a TIME WITH TIME ZONE to an integer sort key. SQL: `timetz_byte_comparable`."""
        return self._expr._call("timetz_byte_comparable")

    def timezone(self) -> Expr:
        """The time zone offset, in seconds. SQL: `timezone`."""
        return self._expr._call("timezone")

    def timezone_hour(self) -> Expr:
        """Extract the timezone_hour component from a date or timestamp. SQL: `timezone_hour`."""
        return self._expr._call("timezone_hour")

    def timezone_minute(self) -> Expr:
        """Extract the timezone_minute component from a date or timestamp. SQL: `timezone_minute`."""
        return self._expr._call("timezone_minute")

    def trunc(self, part: object, *args: object) -> Expr:
        """Truncate to specified precision. Arguments: part. SQL: `date_trunc`."""
        return self._expr._call_at("date_trunc", 1, part, *args)

    def week(self) -> Expr:
        """Extract the week component from a date or timestamp. SQL: `week`."""
        return self._expr._call("week")

    def weekday(self) -> Expr:
        """Extract the weekday component from a date or timestamp. SQL: `weekday`."""
        return self._expr._call("weekday")

    def weekofyear(self) -> Expr:
        """Extract the weekofyear component from a date or timestamp. SQL: `weekofyear`."""
        return self._expr._call("weekofyear")

    def year(self) -> Expr:
        """Extract the year component from a date or timestamp. SQL: `year`."""
        return self._expr._call("year")

    def yearweek(self) -> Expr:
        """Extract the yearweek component from a date or timestamp. SQL: `yearweek`."""
        return self._expr._call("yearweek")


class ListMethods(_Namespace):
    """List functions, applied to this expression as the list."""

    __slots__ = ()

    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {
        "aggregate": ("list_aggregate", 0, ["ANY[]", "VARCHAR"]),
        "any_value": ("list_any_value", 0, []),
        "append": ("list_append", 0, []),
        "approx_count_distinct": ("list_approx_count_distinct", 0, []),
        "avg": ("list_avg", 0, []),
        "bit_and": ("list_bit_and", 0, []),
        "bit_or": ("list_bit_or", 0, []),
        "bit_xor": ("list_bit_xor", 0, []),
        "bool_and": ("list_bool_and", 0, []),
        "bool_or": ("list_bool_or", 0, []),
        "contains": ("list_contains", 0, ["T[]", "T"]),
        "cosine_distance": ("list_cosine_distance", 0, ["FLOAT[]", "FLOAT[]"]),
        "cosine_similarity": ("list_cosine_similarity", 0, ["DOUBLE[]", "DOUBLE[]"]),
        "count": ("list_count", 0, []),
        "distance": ("list_distance", 0, ["FLOAT[]", "FLOAT[]"]),
        "distinct": ("list_distinct", 0, ["T[]"]),
        "entropy": ("list_entropy", 0, []),
        "extract": ("list_extract", 0, ["T[]", "BIGINT"]),
        "first": ("list_first", 0, []),
        "flatten": ("flatten", 0, ["T[][]"]),
        "grade_up": ("list_grade_up", 0, ["ANY[]"]),
        "has_all": ("list_has_all", 0, ["T[]", "T[]"]),
        "has_any": ("list_has_any", 0, ["T[]", "T[]"]),
        "histogram": ("list_histogram", 0, []),
        "inner_product": ("list_inner_product", 0, ["FLOAT[]", "FLOAT[]"]),
        "intersect": ("list_intersect", 0, ["T[]", "T[]"]),
        "kurtosis": ("list_kurtosis", 0, []),
        "kurtosis_pop": ("list_kurtosis_pop", 0, []),
        "last": ("list_last", 0, []),
        "mad": ("list_mad", 0, []),
        "max": ("list_max", 0, []),
        "median": ("list_median", 0, []),
        "min": ("list_min", 0, []),
        "mode": ("list_mode", 0, []),
        "negative_inner_product": ("list_negative_inner_product", 0, ["FLOAT[]", "FLOAT[]"]),
        "position": ("list_position", 0, ["T[]", "T"]),
        "prepend": ("list_prepend", 1, []),
        "product": ("list_product", 0, []),
        "resize": ("list_resize", 0, ["ANY[]", "ANY"]),
        "reverse": ("list_reverse", 0, []),
        "reverse_sort": ("list_reverse_sort", 0, ["ANY[]"]),
        "select": ("list_select", 0, ["T[]", "BIGINT[]"]),
        "sem": ("list_sem", 0, []),
        "skewness": ("list_skewness", 0, []),
        "sort": ("list_sort", 0, ["ANY[]"]),
        "stddev_pop": ("list_stddev_pop", 0, []),
        "stddev_samp": ("list_stddev_samp", 0, []),
        "string_agg": ("list_string_agg", 0, []),
        "sum": ("list_sum", 0, []),
        "unique": ("list_unique", 0, ["ANY[]"]),
        "var_pop": ("list_var_pop", 0, []),
        "var_samp": ("list_var_samp", 0, []),
        "where": ("list_where", 0, ["T[]", "BOOLEAN[]"]),
    }

    def aggregate(self, *args: object) -> Expr:
        """Executes the aggregate function `function_name` on the elements of `l.

        Arguments: function_name. SQL: `list_aggregate`.
        """
        return self._expr._call("list_aggregate", *args)

    def any_value(self) -> Expr:
        """The `list_any_value` function. SQL: `list_any_value`."""
        return self._expr._call("list_any_value")

    def append(self, *args: object) -> Expr:
        """The `list_append` function. Arguments: e. SQL: `list_append`."""
        return self._expr._call("list_append", *args)

    def approx_count_distinct(self) -> Expr:
        """The `list_approx_count_distinct` function. SQL: `list_approx_count_distinct`."""
        return self._expr._call("list_approx_count_distinct")

    def avg(self) -> Expr:
        """The `list_avg` function. SQL: `list_avg`."""
        return self._expr._call("list_avg")

    def bit_and(self) -> Expr:
        """The `list_bit_and` function. SQL: `list_bit_and`."""
        return self._expr._call("list_bit_and")

    def bit_or(self) -> Expr:
        """The `list_bit_or` function. SQL: `list_bit_or`."""
        return self._expr._call("list_bit_or")

    def bit_xor(self) -> Expr:
        """The `list_bit_xor` function. SQL: `list_bit_xor`."""
        return self._expr._call("list_bit_xor")

    def bool_and(self) -> Expr:
        """The `list_bool_and` function. SQL: `list_bool_and`."""
        return self._expr._call("list_bool_and")

    def bool_or(self) -> Expr:
        """The `list_bool_or` function. SQL: `list_bool_or`."""
        return self._expr._call("list_bool_or")

    def contains(self, *args: object) -> Expr:
        """Returns true if the list contains the element. Arguments: element. SQL: `list_contains`."""
        return self._expr._call("list_contains", *args)

    def cosine_distance(self, *args: object) -> Expr:
        """Computes the cosine distance between two same-sized lists.

        Arguments: list2. SQL: `list_cosine_distance`.
        """
        return self._expr._call("list_cosine_distance", *args)

    def cosine_similarity(self, *args: object) -> Expr:
        """Computes the cosine similarity between two same-sized lists.

        Arguments: list2. SQL: `list_cosine_similarity`.
        """
        return self._expr._call("list_cosine_similarity", *args)

    def count(self) -> Expr:
        """The `list_count` function. SQL: `list_count`."""
        return self._expr._call("list_count")

    def distance(self, *args: object) -> Expr:
        """Calculates the Euclidean distance between two points with coordinates.

        Arguments: list2. SQL: `list_distance`.
        """
        return self._expr._call("list_distance", *args)

    def distinct(self) -> Expr:
        """Removes all duplicates and `NULL` values from a list. SQL: `list_distinct`."""
        return self._expr._call("list_distinct")

    def entropy(self) -> Expr:
        """The `list_entropy` function. SQL: `list_entropy`."""
        return self._expr._call("list_entropy")

    def extract(self, *args: object) -> Expr:
        """Extract the `index`th (1-based) value from the list. Arguments: index. SQL: `list_extract`."""
        return self._expr._call("list_extract", *args)

    def first(self) -> Expr:
        """The `list_first` function. SQL: `list_first`."""
        return self._expr._call("list_first")

    def flatten(self) -> Expr:
        """Flattens a nested list by one level. SQL: `flatten`."""
        return self._expr._call("flatten")

    def grade_up(self) -> Expr:
        """Works like list_sort, but the results are the indexes that correspond. SQL: `list_grade_up`."""
        return self._expr._call("list_grade_up")

    def has_all(self, *args: object) -> Expr:
        """Returns true if all elements of list2 are in list1. Arguments: list2. SQL: `list_has_all`."""
        return self._expr._call("list_has_all", *args)

    def has_any(self, *args: object) -> Expr:
        """Returns true if the lists have any element in common. Arguments: list2. SQL: `list_has_any`."""
        return self._expr._call("list_has_any", *args)

    def histogram(self) -> Expr:
        """The `list_histogram` function. SQL: `list_histogram`."""
        return self._expr._call("list_histogram")

    def inner_product(self, *args: object) -> Expr:
        """Computes the inner product between two same-sized lists. Arguments: list2. SQL: `list_inner_product`."""
        return self._expr._call("list_inner_product", *args)

    def intersect(self, *args: object) -> Expr:
        """Returns a list containing the distinct elements that are present in b.

        Arguments: list2. SQL: `list_intersect`.
        """
        return self._expr._call("list_intersect", *args)

    def kurtosis(self) -> Expr:
        """The `list_kurtosis` function. SQL: `list_kurtosis`."""
        return self._expr._call("list_kurtosis")

    def kurtosis_pop(self) -> Expr:
        """The `list_kurtosis_pop` function. SQL: `list_kurtosis_pop`."""
        return self._expr._call("list_kurtosis_pop")

    def last(self) -> Expr:
        """The `list_last` function. SQL: `list_last`."""
        return self._expr._call("list_last")

    def mad(self) -> Expr:
        """The `list_mad` function. SQL: `list_mad`."""
        return self._expr._call("list_mad")

    def max(self) -> Expr:
        """The `list_max` function. SQL: `list_max`."""
        return self._expr._call("list_max")

    def median(self) -> Expr:
        """The `list_median` function. SQL: `list_median`."""
        return self._expr._call("list_median")

    def min(self) -> Expr:
        """The `list_min` function. SQL: `list_min`."""
        return self._expr._call("list_min")

    def mode(self) -> Expr:
        """The `list_mode` function. SQL: `list_mode`."""
        return self._expr._call("list_mode")

    def negative_inner_product(self, *args: object) -> Expr:
        """Computes the negative inner product between two same-sized lists.

        Arguments: list2. SQL: `list_negative_inner_product`.
        """
        return self._expr._call("list_negative_inner_product", *args)

    def position(self, *args: object) -> Expr:
        """Returns the index of the `element` if the `list` contains the `element`.

        Arguments: element. SQL: `list_position`.
        """
        return self._expr._call("list_position", *args)

    def prepend(self, e: object, *args: object) -> Expr:
        """The `list_prepend` function. Arguments: e. SQL: `list_prepend`."""
        return self._expr._call_at("list_prepend", 1, e, *args)

    def product(self) -> Expr:
        """The `list_product` function. SQL: `list_product`."""
        return self._expr._call("list_product")

    def resize(self, *args: object) -> Expr:
        """Resizes the `list` to contain `size` elements. Arguments: size[. SQL: `list_resize`."""
        return self._expr._call("list_resize", *args)

    def reverse(self) -> Expr:
        """The `list_reverse` function. SQL: `list_reverse`."""
        return self._expr._call("list_reverse")

    def reverse_sort(self) -> Expr:
        """Sorts the elements of the list in reverse order. SQL: `list_reverse_sort`."""
        return self._expr._call("list_reverse_sort")

    def select(self, *args: object) -> Expr:
        """Returns a list based on the elements selected by the `index_list`.

        Arguments: index_list. SQL: `list_select`.
        """
        return self._expr._call("list_select", *args)

    def sem(self) -> Expr:
        """The `list_sem` function. SQL: `list_sem`."""
        return self._expr._call("list_sem")

    def skewness(self) -> Expr:
        """The `list_skewness` function. SQL: `list_skewness`."""
        return self._expr._call("list_skewness")

    def sort(self) -> Expr:
        """Sorts the elements of the list. SQL: `list_sort`."""
        return self._expr._call("list_sort")

    def stddev_pop(self) -> Expr:
        """The `list_stddev_pop` function. SQL: `list_stddev_pop`."""
        return self._expr._call("list_stddev_pop")

    def stddev_samp(self) -> Expr:
        """The `list_stddev_samp` function. SQL: `list_stddev_samp`."""
        return self._expr._call("list_stddev_samp")

    def string_agg(self) -> Expr:
        """The `list_string_agg` function. SQL: `list_string_agg`."""
        return self._expr._call("list_string_agg")

    def sum(self) -> Expr:
        """The `list_sum` function. SQL: `list_sum`."""
        return self._expr._call("list_sum")

    def unique(self) -> Expr:
        """Counts the unique elements of a `list`. SQL: `list_unique`."""
        return self._expr._call("list_unique")

    def var_pop(self) -> Expr:
        """The `list_var_pop` function. SQL: `list_var_pop`."""
        return self._expr._call("list_var_pop")

    def var_samp(self) -> Expr:
        """The `list_var_samp` function. SQL: `list_var_samp`."""
        return self._expr._call("list_var_samp")

    def where(self, *args: object) -> Expr:
        """Returns a list with the `BOOLEAN`s in `mask_list` applied as a mask t.

        Arguments: mask_list. SQL: `list_where`.
        """
        return self._expr._call("list_where", *args)
