"""Generate duckdb/_aggregates.py: the aggregate shortcuts on Expr, as real methods.

They used to be served by `__getattr__` over a table, which typed every call
as Any, hid the names from completion, and could not be checked. The table
lives in func_namespaces.toml under `[aggregates]`; the methods are written
out so they can be. Every entry is checked to exist as an aggregate in the
engine's catalog, so a bump that drops one fails here.

    gen_aggregates.py [--check]
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path


#: Method name to SQL function. The Python name follows pandas and Polars where
#: they agree with each other; the SQL name is DuckDB's.
def load_aggregates() -> dict[str, tuple[str, str]]:
    """The aggregate table, from the shared function table beside this script."""
    table = tomllib.loads((Path(__file__).with_name("func_namespaces.toml")).read_text())
    return {method: (spec["sql"], spec["doc"]) for method, spec in table["aggregates"]["methods"].items()}


AGGREGATES = load_aggregates()

HEADER = '''"""Aggregate shortcuts on Expr, one real method per function.

Generated by scripts/gen_aggregates.py. Do not edit; regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class AggregateMethods:
    """The aggregate functions reachable as methods, so `col("v").sum()` reads as SQL does.

    Each becomes a window function with `.over()`. Anything not here is a
    `fn()` call away.
    """

    #: Method name to SQL function, the table these methods were written from.
    _CALLABLES: ClassVar[dict[str, str]] = {
'''


def render() -> str:
    """The module text."""
    out = [HEADER]
    for method, (function, _) in AGGREGATES.items():
        out.append(f'        "{method}": "{function}",\n')
    out.append("    }\n\n")
    out.append("    def _call(self, function: str, *args: object) -> Expr:  # pragma: no cover - Expr defines it\n")
    out.append("        raise NotImplementedError\n")
    for method, (function, doc) in AGGREGATES.items():
        out.append(f"\n    def {method}(self, *args: object) -> Expr:\n")
        out.append(f'        """{doc} SQL: `{function}`."""\n')
        out.append(f'        return self._call("{function}", *args)\n')
    return "".join(out)


def verify(connection: object) -> list[str]:
    """The table entries the engine's catalog has no aggregate for."""
    import duckdb

    query = "SELECT DISTINCT function_name FROM duckdb_functions() WHERE function_type = 'aggregate'"
    known = {row[0] for row in duckdb.sql(query).rows(connection)}  # type: ignore[arg-type]
    return sorted({function for function, _ in AGGREGATES.values()} - known)


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    missing = verify(duckdb.connect())
    if missing:
        print(f"not aggregate functions in this engine's catalog: {', '.join(missing)}", file=sys.stderr)
        return 1
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "_aggregates.py"
    text = render()
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_aggregates.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f"wrote {target} ({len(AGGREGATES)} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
