"""Generate src/duckdb/frame/_aggregates.py from func_namespaces.toml, so the aggregate methods type and complete."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path


def load_aggregates() -> dict[str, tuple[str, str]]:
    """The aggregate table, from the shared function table beside this script."""
    table = tomllib.loads((Path(__file__).with_name("func_namespaces.toml")).read_text())
    return {method: (spec["sql"], spec["doc"]) for method, spec in table["aggregates"]["methods"].items()}


AGGREGATES = load_aggregates()

HEADER = '''\
"""One method per aggregate function, generated by scripts/gen_aggregates.py; never edit here."""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class AggregateMethods:
    """The aggregate functions as methods; `.over()` makes each a window function, and `fn()` reaches the rest."""

    #: Method name to SQL function, the table these methods were written from.
    _CALLABLES: ClassVar[dict[str, str]] = {
'''


def render() -> str:
    """The module text."""
    out = [HEADER]
    for method, (function, _) in AGGREGATES.items():
        out.append(f'        "{method}": "{function}",\n')
    out.append("    }\n\n")
    out.append("    def _call(self, function: str, *args: object) -> Expr:  # pragma: no cover (Expr defines it)\n")
    out.append("        raise NotImplementedError\n")
    for method, (function, doc) in AGGREGATES.items():
        out.append(f"\n    def {method}(self, *args: object) -> Expr:\n")
        out.append(f'        """{doc} SQL: `{function}`."""\n')
        out.append(f'        return self._call("{function}", *args)\n')
    return "".join(out)


def verify(connection: object) -> list[str]:
    """The table entries DuckDB's catalog has no aggregate for."""
    import duckdb

    query = "SELECT DISTINCT function_name FROM duckdb_functions() WHERE function_type = 'aggregate'"
    known = {row[0] for row in duckdb.frame.sql(query).rows(connection)}  # type: ignore[arg-type]
    return sorted({function for function, _ in AGGREGATES.values()} - known)


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    missing = verify(duckdb.frame.connect())
    if missing:
        print(f"no aggregate in this engine's catalog for: {', '.join(missing)}", file=sys.stderr)
        return 1
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "frame" / "_aggregates.py"
    text = render()
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_aggregates.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f"wrote {target} ({len(AGGREGATES)} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
