"""Generate src/duckdb/frame/_keywords.py from `duckdb_keywords()`: which names need quoting is DuckDB's to say."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HEADER = '''\
"""DuckDB's SQL keywords by category, generated by scripts/gen_keywords.py; never edit here."""

from __future__ import annotations

#: Every keyword DuckDB's parser knows, lowercased. A name here is quoted as an identifier whatever its category.
KEYWORD_CATEGORY: dict[str, str] = {
'''

FOOTER = """}

KEYWORDS: frozenset[str] = frozenset(KEYWORD_CATEGORY)
"""


def keywords(connection: object) -> list[tuple[str, str]]:
    """DuckDB's keywords and their categories, sorted by name."""
    import duckdb

    query = (
        "SELECT lower(keyword_name), string_agg(DISTINCT keyword_category, '/' ORDER BY keyword_category) "
        "FROM duckdb_keywords() GROUP BY 1 ORDER BY 1"
    )
    return [(str(name), str(category)) for name, category in duckdb.frame.sql(query).rows(connection)]  # type: ignore[arg-type]


def render(connection: object) -> str:
    """The module text for this build's keywords."""
    rows = keywords(connection)
    if not rows:
        message = "duckdb_keywords() returned nothing"
        raise SystemExit(message)
    body = "".join(f'    "{name}": "{category}",\n' for name, category in rows)
    return HEADER + body + FOOTER


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    text = render(duckdb.frame.connect())
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "frame" / "_keywords.py"
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_keywords.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f"wrote {target} ({text.count(chr(10)) - HEADER.count(chr(10)) - FOOTER.count(chr(10))} keywords)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
