"""Generate duckdb/_namespaces.py: the `.str`, `.dt` and `.list` methods on Expr.

Read from the engine's own catalog, `duckdb_functions()`, so the surface is
whatever the engine this package links against actually has. Re-run after
bumping engine.pin.

    gen_namespaces.py [--check]

What goes where:

- `.str`: functions the catalog files under string, regex or text similarity,
  whose first parameter is the string.
- `.dt`: functions every shortest overload of which takes a date, time,
  timestamp or interval, first or after a specifier such as the `'month'`
  of `date_trunc` or the `INTERVAL` of `time_bucket`. The method puts the
  expression where the bound overload wants it.
- `.list`: functions the catalog files under list that take a list, and the
  `list_*` macros, which carry no types but name their list parameter `l`.
  The `list_` prefix is dropped from the method name.

Each method binds one overload family: the shortest overloads. Where the
overloads of one name disagree about where the subject goes (`strftime` takes
the timestamp first in one family and second in another, `timezone` extracts
with one argument and converts with two) the generator refuses to choose and
stops, until CHOICES names the family and the docstring for it.

Left out everywhere: functions taking a lambda (this library has no lambda
expression), names that are not Python identifiers, and aliases of a function
already included, so `array_sort` does not duplicate `list_sort`. Two
functions landing on one method name is an error here, not a silent choice.

Each class also carries a SPEC table, method name to (function, position of
the expression among the arguments, parameter types of the bound overload),
which the tests use to call every method against the engine.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
from pathlib import Path
from typing import Any

IDENTIFIER = re.compile(r"^[a-z][a-z0-9_]*$")
TEMPORAL = {
    "DATE",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP_NS",
    "TIMESTAMPTZ_NS",
    "TIME",
    "TIME WITH TIME ZONE",
    "TIME_NS",
    "INTERVAL",
}
#: Where the subject goes in a specifier-first signature, and what the
#: specifier is. `INTERVAL` first is a specifier for `time_bucket` and a
#: subject for `to_days`, so a second-position temporal wins over it.
SPECIFIER = {"VARCHAR", "INTERVAL"}
#: Names whose overloads disagree about where the subject goes. Each names
#: the subject position to bind and the docstring for that family.
CHOICES: dict[str, tuple[int, str]] = {
    "strftime": (0, "Format as text, with a strftime pattern"),
    "timezone": (0, "The time zone offset, in seconds"),
}

HEADER = '''"""The `.str`, `.dt` and `.list` methods on Expr, one per engine function.

Generated by scripts/gen_namespaces.py from duckdb_functions(). Do not edit;
regenerate after bumping engine.pin.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class _Namespace:
    """A group of functions applied to one expression."""

    __slots__ = ("_expr",)

    #: Method name to (function, position of the expression, parameter types).
    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {}

    def __init__(self, expr: Expr) -> None:
        self._expr = expr
'''


def catalog(connection: object) -> list[tuple[Any, ...]]:
    """Every scalar function and macro, every overload, shortest first."""
    from duckdb import sql

    query = """
        SELECT function_name, function_type, alias_of, parameters, parameter_types, categories, description
        FROM duckdb_functions()
        WHERE function_type IN ('scalar', 'macro') AND len(parameters) > 0
          AND NOT list_contains(parameter_types, 'LAMBDA')
        ORDER BY function_name, len(parameter_types)
    """
    return sql(query).fetchall(connection)  # type: ignore[arg-type]


class Entry:
    """One method: what it calls and how."""

    def __init__(self, function: str, position: int, types: list[str], params: list[str], doc: str) -> None:
        self.function = function
        self.position = position
        self.types = types
        self.params = params
        self.doc = doc


def _one_line(description: str | None) -> str:
    """The first sentence of a description, short enough for a docstring line."""
    text = (description or "").strip().split("\n")[0].replace('"', "'")
    first = text.split(". ")[0].rstrip(".")
    if len(first) > 72:
        first = first[:69].rstrip() + "..."
    return first


def classify(rows: list[tuple[Any, ...]]) -> dict[str, dict[str, Entry]]:
    """Method name to entry, per namespace."""
    by_name: dict[str, list[tuple[Any, ...]]] = {}
    for row in rows:
        by_name.setdefault(row[0], []).append(row)
    groups: dict[str, dict[str, Entry]] = {"str": {}, "dt": {}, "list": {}}
    placed: dict[tuple[str, str], str] = {}

    def place(group: str, method: str, entry: Entry) -> None:
        taken = groups[group].get(method)
        if taken is not None and taken.function != entry.function:
            message = f"{group}.{method} would name both {taken.function} and {entry.function}"
            raise SystemExit(message)
        groups[group][method] = entry
        placed[(group, entry.function)] = method

    # `datediff` is `date_diff` under another spelling, registered without an
    # alias link. One method each is enough.
    squashed = {name.replace("_", "") for name in by_name if "_" in name}
    for name, overloads in by_name.items():
        if not IDENTIFIER.match(name) or keyword.iskeyword(name):
            continue
        kind, alias_of = overloads[0][1], overloads[0][2]
        if alias_of and alias_of in by_name:
            continue  # the canonical name is placed instead
        if "_" not in name and name in squashed:
            continue
        shortest = overloads[0]
        params, categories = list(shortest[3]), set(shortest[5] or [])
        doc = _one_line(shortest[6]) or f"The `{name}` function."
        if kind == "macro":
            if name.startswith("list_"):
                # No types on a macro, but its list is the parameter named `l`.
                position = params.index("l") if "l" in params else 0
                others = [p for i, p in enumerate(params) if i != position]
                place("list", name.removeprefix("list_"), Entry(name, position, [], others, doc))
            continue
        for group in ("dt", "str", "list"):
            entry = _entry_for(name, overloads, group, categories, doc)
            if entry is not None:
                place(group, _method_name(name, group), entry)
    return groups


def _subject(types: list[str], group: str) -> int | None:
    """Where the subject of `group` sits in a signature, or None if absent."""
    if group == "dt":
        # A temporal after a specifier is the subject; otherwise a temporal
        # first is. Text first is always a specifier (`date_trunc('month', x)`);
        # an interval first is one only before a date or time
        # (`time_bucket(INTERVAL, ts)`), since `add(INTERVAL, INTERVAL)` is
        # about its first argument.
        if len(types) > 1 and types[0] == "VARCHAR" and types[1] in TEMPORAL:
            return 1
        if len(types) > 1 and types[0] == "INTERVAL" and types[1] in TEMPORAL - {"INTERVAL"}:
            return 1
        return 0 if types and types[0] in TEMPORAL else None
    if group == "str":
        return 0 if types and types[0] == "VARCHAR" else None
    return next((i for i, t in enumerate(types) if t.endswith("[]")), None)


def _method_name(name: str, group: str) -> str:
    if group == "dt":
        return name.removeprefix("date_")
    if group == "list":
        return name.removeprefix("list_")
    return name


def _entry_for(name: str, overloads: list[tuple[Any, ...]], group: str, categories: set[str], doc: str) -> Entry | None:
    """The method for `name` in `group`, or None if it does not belong there."""
    if group == "str" and not (categories & {"string", "regex", "text_similarity"}):
        return None
    if group == "list" and "list" not in categories:
        return None
    if group != "list" and name.startswith(("list_", "array_")):
        return None
    if group == "list" and name.startswith("array_"):
        return None
    # The catalog does not file date functions, so membership is by
    # signature: every overload must be about a date, time or interval.
    # `isfinite` has a DATE overload and a DOUBLE one; it is not.
    if group == "dt" and not all(_subject(list(o[4]), "dt") is not None for o in overloads):
        return None
    all_positions = {found for o in overloads if (found := _subject(list(o[4]), group)) is not None}
    if not all_positions:
        return None
    choice = CHOICES.get(name)
    if len(all_positions) > 1 and choice is None:
        message = (
            f"{name} takes its {group} subject at positions {sorted(all_positions)} in different "
            f"overloads; add it to CHOICES with the position and docstring to bind"
        )
        raise SystemExit(message)
    position = choice[0] if choice else all_positions.pop()
    bound = next(o for o in overloads if _subject(list(o[4]), group) == position)
    types, params = list(bound[4]), list(bound[3])
    others = [p for i, p in enumerate(params) if i != position]
    return Entry(name, position, types, others, choice[1] if choice else doc)


CLASSES = {"str": "StringMethods", "dt": "DateMethods", "list": "ListMethods"}
BLURB = {
    "str": "Text functions, applied to this expression as the string.",
    "dt": "Date and time functions, applied to this expression as the date, time or timestamp.",
    "list": "List functions, applied to this expression as the list.",
}


def render(groups: dict[str, dict[str, Entry]]) -> str:
    """The module text."""
    out = [HEADER]
    for key, cls in CLASSES.items():
        out.append(f"\n\nclass {cls}(_Namespace):\n")
        out.append(f'    """{BLURB[key]}"""\n\n')
        out.append("    __slots__ = ()\n\n")
        out.append("    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {\n")
        for method, entry in sorted(groups[key].items()):
            out.append(f'        "{method}": ("{entry.function}", {entry.position}, {json.dumps(entry.types)}),\n')
        out.append("    }\n")
        for method, entry in sorted(groups[key].items()):
            usage = f" Arguments: {', '.join(entry.params)}." if entry.params else ""
            doc = entry.doc.rstrip(".")
            if entry.position > 0:
                leading = ", ".join(f"{p}: object" for p in entry.params[: entry.position])
                signature = f"(self, {leading}, *args: object)"
                names = ", ".join(entry.params[: entry.position])
                call = f'self._expr._call_at("{entry.function}", {entry.position}, {names}, *args)'
            elif entry.params:
                signature = "(self, *args: object)"
                call = f'self._expr._call("{entry.function}", *args)'
            else:
                signature = "(self)"
                call = f'self._expr._call("{entry.function}")'
            out.append(f"\n    def {method}{signature} -> Expr:\n")
            line = f'        """{doc}.{usage} SQL: `{entry.function}`."""'
            if len(line) > 118:
                line = f'        """{doc}.\n\n        {usage.strip()} SQL: `{entry.function}`.\n        """'
            out.append(line + "\n")
            out.append(f"        return {call}\n")
    return "".join(out)


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    groups = classify(catalog(duckdb.connect()))
    text = render(groups)
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "_namespaces.py"
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_namespaces.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    counts = ", ".join(f"{k}={len(v)}" for k, v in groups.items())
    print(f"wrote {target} ({counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
