"""Generate src/duckdb/frame/_func_namespaces.py from func_namespaces.toml, checked against the function catalog."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

TEMPORAL = {
    "DATE",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP_NS",
    "TIMESTAMPTZ_NS",
    "TIME",
    "TIME WITH TIME ZONE",
    "TIME_NS",
    "INTERVAL",
}

LINE_LIMIT = 120

CLASSES = {"str": "StrExpr", "dt": "DtExpr", "list": "ListExpr", "json": "JsonExpr"}
BASES = {"str": "FamilyExpr", "dt": "FamilyExpr", "list": "FamilyExpr", "json": "StrExpr"}

HEADER = '''\
"""The .str(), .dt(), .list() and .json() methods, generated by scripts/gen_func_namespaces.py; never edit here."""

from __future__ import annotations

from typing import ClassVar

from .expr import Expr, FamilyExpr
'''


class Problem(Exception):
    """A table entry DuckDB's catalog cannot honor as declared."""


def load_table() -> dict[str, Any]:
    """The declared table, from beside this script."""
    return tomllib.loads((Path(__file__).with_name("func_namespaces.toml")).read_text())


def catalog(connection: object) -> dict[str, list[tuple[Any, ...]]]:
    """Every scalar function and macro by name: (type, parameters, parameter_types, return_type, description)."""
    from duckdb.frame import sql

    query = """
        SELECT function_name, function_type, parameters, parameter_types, return_type, description
        FROM duckdb_functions()
        WHERE function_type IN ('scalar', 'macro')
        ORDER BY function_name, len(parameter_types)
    """
    by_name: dict[str, list[tuple[Any, ...]]] = {}
    for row in sql(query).rows(connection):  # type: ignore[arg-type]
        by_name.setdefault(row[0], []).append(row)
    return by_name


def coverage(connection: object, covers: dict[str, str]) -> dict[str, set[str]]:
    """The function names each family claims to cover, per its `covers` rule."""
    from duckdb.frame import sql

    named = """
        SELECT DISTINCT function_name AS f, categories, parameter_types
        FROM duckdb_functions()
        WHERE function_type IN ('scalar', 'macro')
          AND regexp_matches(function_name, '^[a-z][a-z0-9_]*$')
          AND function_name NOT LIKE '\\_\\_%' ESCAPE '\\'
          AND (alias_of IS NULL OR alias_of = '' OR alias_of = function_name)
    """
    # Categories and parameter types are empty on a macro, so only the list rule's name match catches one.
    rules = {
        "string": "list_has_any(categories, ['string', 'regex', 'text_similarity'])",
        "temporal": (
            "len(parameter_types) > 0 AND list_has_any("
            + str(sorted(TEMPORAL)).replace('"', "'")
            + ", parameter_types)"
        ),
        "list": "list_has_any(categories, ['list', 'lambda']) OR f LIKE 'list\\_%' ESCAPE '\\'",
        "json": "f LIKE 'json%'",
    }
    out: dict[str, set[str]] = {}
    for family, rule in covers.items():
        rows = sql(f"SELECT DISTINCT f FROM ({named}) WHERE {rules[rule]}").rows(connection)  # type: ignore[arg-type]
        out[family] = {row[0] for row in rows}
    return out


def _one_line(description: str | None) -> str:
    """The first sentence of a catalog description, short enough for a docstring."""
    text = (description or "").strip().split("\n")[0].replace('"', "'")
    first = text.split(". ")[0].rstrip(".")
    if len(first) > 72:
        first = first[:69].rstrip() + "..."
    return first


def _sentence(doc: str) -> str:
    """The doc closed with exactly one period, leaving a truncation ellipsis be."""
    return doc if doc.endswith("...") else doc.rstrip(".") + "."


def _fit(doc: str, room: int) -> str:
    """The doc cut to `room` characters, with an ellipsis where it was cut."""
    return doc if len(doc) <= room else doc[: room - 3].rstrip(" .") + "..."


def _return_class(return_type: str) -> str:
    """The family a SQL return type comes back in, as the catalog spells it."""
    if return_type.endswith("]"):
        return "ListExpr"
    if return_type == "JSON":
        return "JsonExpr"
    if return_type == "VARCHAR":
        return "StrExpr"
    if return_type in TEMPORAL:
        return "DtExpr"
    return "Expr"


def _reserved() -> set[str]:
    """Every Expr attribute a family method must not shadow; the aggregate shortcuts are the deliberate exception."""
    from duckdb.frame._aggregates import AggregateMethods
    from duckdb.frame.expr import Expr, FamilyExpr, FuncNamespaces

    aggregates = {name for name in vars(AggregateMethods) if not name.startswith("_")}
    names: set[str] = set()
    for cls in (Expr, FamilyExpr, FuncNamespaces):
        names |= {name for name in vars(cls) if not name.startswith("__")}
    return names - aggregates


def _bound_overload(
    entries: list[tuple[Any, ...]], subject: int, family: str, pin: list[str] | None
) -> tuple[str, list[str], list[str], str, str]:
    """The overload a method resolves to: (kind, parameter types, names, return type, description)."""
    subjects: dict[str, Callable[[str], bool]] = {
        "str": lambda t: t in {"VARCHAR", "JSON", "ANY"},
        "json": lambda t: t in {"VARCHAR", "JSON", "ANY"},
        "list": lambda t: t.endswith("]") or t == "ANY",
        "dt": lambda t: t in TEMPORAL or t == "ANY",
    }
    fits = subjects[family]
    scalars = [e for e in entries if e[1] == "scalar"]
    if pin is not None:
        for entry in scalars:
            if list(entry[3]) == pin:
                return "scalar", list(entry[3]), list(entry[2]), entry[4] or "", entry[5] or ""
        message = f"the pinned overload {pin} is not in this engine's catalog"
        raise Problem(message)
    fitting = [e for e in scalars if len(e[3]) > subject and fits(e[3][subject])]
    if fitting:
        classes = sorted({_return_class(e[4] or "") for e in fitting})
        if len(classes) > 1:
            listed = ", ".join(classes)
            message = f"fitting overloads disagree on the return class ({listed}); pin one with types = [...]"
            raise Problem(message)
        # The shortest and plainest of the agreeing forms: json_extract(j, path) over json_extract(j, paths[]).
        entry = min(
            fitting, key=lambda e: (len(e[3]), sum((t or "").endswith("]") for t in e[3]), [t or "" for t in e[3]])
        )
        return "scalar", list(entry[3]), list(entry[2]), entry[4] or "", entry[5] or ""
    for entry in entries:
        if entry[1] == "macro" and len(entry[2]) > subject:
            return "macro", [], list(entry[2]), "", entry[5] or ""
    message = f"no overload takes the subject at position {subject}"
    raise Problem(message)


def build(connection: object, table: dict[str, Any] | None = None) -> tuple[dict[str, Any], dict[str, list[str]]]:
    """Verify the table against the catalog; return it with resolved entries, and the problems."""
    table = load_table() if table is None else table
    by_name = catalog(connection)
    reserved = _reserved()
    problems: list[str] = []
    resolved: dict[str, Any] = {}
    for family in CLASSES:
        section = table[family]
        methods: dict[str, dict[str, Any]] = {}
        for method, spec in sorted(section["methods"].items()):
            function = spec["sql"]
            subject = int(spec.get("subject", 0))
            if method in reserved:
                problems.append(f"{family}.{method}: shadows Expr's own `{method}`; pick another name")
                continue
            entries = by_name.get(function)
            if not entries:
                problems.append(f"{family}.{method}: {function} is not in this engine's catalog")
                continue
            pin = [str(t) for t in spec["types"]] if "types" in spec else None
            try:
                kind, types, params, return_type, description = _bound_overload(entries, subject, family, pin)
            except Problem as problem:
                problems.append(f"{family}.{method}: {problem}")
                continue
            declared = spec.get("returns")
            if declared is not None and kind == "scalar":
                problems.append(
                    f"{family}.{method}: `returns` is declared, but {function} is a scalar "
                    f"function and the catalog already says what it returns"
                )
                continue
            if declared is not None and declared not in CLASSES:
                problems.append(f"{family}.{method}: `returns` must be one of {sorted(CLASSES)}, not {declared!r}")
                continue
            # The catalog spells an optional parameter `size[`; the brackets are notation, not part of the name.
            names = [p.strip("[]") for i, p in enumerate(params) if i != subject]
            renamed = spec.get("params")
            if renamed is not None:
                if len(renamed) != len(names):
                    problems.append(
                        f"{family}.{method}: `params` gives {len(renamed)} names where the overload has {len(names)}"
                    )
                    continue
                names = [str(p) for p in renamed]
            methods[method] = {
                "function": function,
                "subject": subject,
                "types": types,
                "params": names,
                "returns": CLASSES[declared] if declared else _return_class(return_type),
                "lambda": int(spec.get("lambda", 0)),
                "doc": spec.get("doc") or _one_line(description) or f"The `{function}` function.",
            }
        resolved[family] = {"blurb": section["blurb"], "methods": methods}
    listed_or_ignored = {
        family: {m["function"] for m in resolved[family]["methods"].values()} | set(table[family].get("ignore", []))
        for family in CLASSES
    }
    for family, claimed in coverage(connection, {f: table[f]["covers"] for f in CLASSES}).items():
        loose = sorted(claimed - listed_or_ignored[family])
        if loose:
            problems.append(
                f"[{family}] covers {len(loose)} catalog functions the table neither lists nor ignores: "
                + ", ".join(loose[:8])
                + ("..." if len(loose) > 8 else "")
            )
    return resolved, {"problems": problems}


def render(resolved: dict[str, Any]) -> str:
    """The module text."""
    out = [HEADER]
    for family, cls in CLASSES.items():
        section = resolved[family]
        out.append(f"\n\nclass {cls}({BASES[family]}):\n")
        out.append(f'    """{section["blurb"]}"""\n\n')
        out.append("    #: Method name to (function, position of the expression, parameter types).\n")
        out.append("    SPEC: ClassVar[dict[str, tuple[str, int, list[str]]]] = {\n")
        for method, m in section["methods"].items():
            types = str(m["types"]).replace("'", '"')
            out.append(f'        "{method}": ("{m["function"]}", {m["subject"]}, {types}),\n')
        out.append("    }\n")
        for method, m in section["methods"].items():
            out.append(_method(method, m))
    return "".join(out)


def _method(method: str, m: dict[str, Any]) -> str:
    """One generated method."""
    wrap = m["returns"]
    tail = f" SQL: `{m['function']}`."
    if m["lambda"]:
        head = f"\n    def {method}(self, function: object, *args: object) -> {wrap}:\n"
        call = f'self._call("{m["function"]}", function, *args)'
    else:
        if m["params"]:
            tail = f" Arguments: {', '.join(m['params'])}." + tail
        subject = m["subject"]
        if subject > 0:
            leading = ", ".join(f"{p}: object" for p in m["params"][:subject])
            head = f"\n    def {method}(self, {leading}, *args: object) -> {wrap}:\n"
            names = ", ".join(m["params"][:subject])
            call = f'self._call_at("{m["function"]}", {subject}, {names}, *args)'
        else:
            head = f"\n    def {method}(self, *args: object) -> {wrap}:\n"
            call = f'self._call("{m["function"]}", *args)'
    room = LINE_LIMIT - len('        """') - len(tail) - len('"""')
    doc = f'        """{_fit(_sentence(m["doc"]), room)}{tail}"""\n'
    body = f"        return {call}\n" if wrap == "Expr" else f"        return {wrap}({call})\n"
    return head + doc + body


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    resolved, report = build(duckdb.frame.connect())
    if report["problems"]:
        print("\n".join(report["problems"]), file=sys.stderr)
        return 1
    text = render(resolved)
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "frame" / "_func_namespaces.py"
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_func_namespaces.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    counts = ", ".join(f"{k}={len(v['methods'])}" for k, v in resolved.items())
    print(f"wrote {target} ({counts})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
