"""Generate duckdb/_aggregates.py: the aggregate shortcuts on Expr, as real methods.

They used to be served by `__getattr__` over a table, which typed every call
as Any, hid the names from completion, and could not be checked. The table is
here; the methods are written out so they can be.

    gen_aggregates.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

#: Method name to SQL function. The Python name follows pandas and Polars where
#: they agree with each other; the SQL name is DuckDB's.
AGGREGATES: dict[str, tuple[str, str]] = {
    "sum": ("sum", "The sum of the values."),
    "mean": ("avg", "The average of the values."),
    "avg": ("avg", "The average of the values. The same as `mean`."),
    "min": ("min", "The smallest value."),
    "max": ("max", "The largest value."),
    "count": ("count", "How many values are not NULL. For rows, use `count_all()`."),
    "median": ("median", "The middle value."),
    "std": ("stddev_samp", "The sample standard deviation."),
    "var": ("var_samp", "The sample variance."),
    "first": ("first", "The first value seen. Order it with `.over()` or `sort` to make that mean something."),
    "last": ("last", "The last value seen."),
    "any_value": ("any_value", "Any one of the values, whichever is cheapest."),
    "bit_and": ("bit_and", "The bitwise AND of the values."),
    "bit_or": ("bit_or", "The bitwise OR of the values."),
    "bool_and": ("bool_and", "Whether every value is true."),
    "bool_or": ("bool_or", "Whether any value is true."),
    "product": ("product", "The product of the values."),
    "string_agg": ("string_agg", "The values joined as text. Pass the separator as an argument."),
    "skewness": ("skewness", "The skewness of the distribution."),
    "kurtosis": ("kurtosis", "The kurtosis of the distribution."),
    "entropy": ("entropy", "The entropy of the distribution."),
    "array_agg": ("array_agg", "The values gathered into a list."),
    "mode": ("mode", "The most frequent value."),
    "quantile": ("quantile_cont", "The value at a quantile, interpolated. Pass the quantile, 0 to 1."),
    "arg_min": ("arg_min", "The value of the argument where this is smallest."),
    "arg_max": ("arg_max", "The value of the argument where this is largest."),
}

HEADER = '''"""Aggregate shortcuts on Expr, one real method per function.

Generated by scripts/gen_aggregates.py. Do not edit; regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from .expr import Expr


class AggregateMethods:
    """The aggregate functions reachable as methods, so `col("v").sum()` reads as SQL does.

    Each becomes a window function with `.over()`. Anything not here is a
    `fn()` call away.
    """

    #: Method name to SQL function, the table these methods were written from.
    _CALLABLES: ClassVar[dict[str, str]] = {
'''


def render() -> str:
    """The module text."""
    out = [HEADER]
    for method, (function, _) in AGGREGATES.items():
        out.append(f'        "{method}": "{function}",\n')
    out.append("    }\n\n")
    out.append("    def _call(self, function: str, *args: object) -> Expr:  # pragma: no cover - Expr defines it\n")
    out.append("        raise NotImplementedError\n")
    for method, (function, doc) in AGGREGATES.items():
        out.append(f"\n    def {method}(self, *args: object) -> Expr:\n")
        out.append(f'        """{doc} SQL: `{function}`."""\n')
        out.append(f'        return self._call("{function}", *args)\n')
    return "".join(out)


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "_aggregates.py"
    text = render()
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_aggregates.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f"wrote {target} ({len(AGGREGATES)} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
