"""Generate duckdb/_error_codes.py from the engine's duckdb_v2.h.

The error codes are engine surface, so they are derived from the header rather
than transcribed. Re-run after bumping engine.pin; the header ships inside the
engine bundle.

    gen_error_codes.py <duckdb_v2.h | engine-bundle> [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ENUM = re.compile(r"typedef enum DUCKDB_V2_ERROR \{(.*?)\n\}", re.S)
MEMBER = re.compile(r"DUCKDB_V2_ERROR_([A-Z_0-9]+)\s*=\s*(\d+)")
# Codes not describing a failure, so they get no exception class.
NOT_ERRORS = {"NONE", "MAX_ENUM"}

HEADER = '''"""Engine error codes, keyed by name.

Generated by scripts/gen_error_codes.py from the engine's duckdb_v2.h.
Do not edit; regenerate after bumping engine.pin.
"""

from __future__ import annotations

'''


def render(header_text: str) -> str:
    """Render the module source for the codes found in a duckdb_v2.h."""
    match = ENUM.search(header_text)
    if match is None:
        message = "no DUCKDB_V2_ERROR enum found in the header"
        raise SystemExit(message)
    members = [(name, int(value)) for name, value in MEMBER.findall(match.group(1))]
    if not members:
        message = "DUCKDB_V2_ERROR enum is empty"
        raise SystemExit(message)

    lines = [HEADER, "ERROR_CODES: dict[str, int] = {\n"]
    lines += [f'    "{name}": {value},\n' for name, value in members if name not in NOT_ERRORS]
    lines.append("}\n")
    return "".join(lines)


def main() -> int:
    """Write or verify the generated module."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source", type=Path, help="duckdb_v2.h, or an engine bundle containing it")
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()

    header = args.source if args.source.is_file() else args.source / "duckdb_v2.h"
    rendered = render(header.read_text())
    out = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "_error_codes.py"

    if args.check:
        current = out.read_text() if out.exists() else ""
        if current != rendered:
            print(f"{out} is stale; re-run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{out} is up to date")
        return 0

    out.write_text(rendered)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
