"""Generate duckdb/_keywords.py: the engine's SQL keywords, by category.

A function name that is a keyword has to be quoted in SQL, and which names
are keywords is the engine's to say. The list is read from the engine's own
`duckdb_keywords()` so it cannot drift from the pinned engine by hand; the
test suite and CI compare the committed file against this generator, so a
bump that changes the list fails until it is regenerated.

    gen_keywords.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HEADER = '''"""The engine's SQL keywords, by category.

Generated by scripts/gen_keywords.py from the engine's `duckdb_keywords()`.
Do not edit; regenerate after bumping engine.pin.
"""

from __future__ import annotations

#: Every keyword the engine's parser knows, lowercased, with its categories
#: (reserved, unreserved, type_function, column_name; a few carry two). A
#: name in this table is quoted when written as an identifier, whatever its
#: category, which is the engine's own rule.
KEYWORD_CATEGORY: dict[str, str] = {
'''

FOOTER = """}

KEYWORDS: frozenset[str] = frozenset(KEYWORD_CATEGORY)
"""


def keywords(connection: object) -> list[tuple[str, str]]:
    """The engine's keywords and their categories, sorted by name."""
    import duckdb

    query = (
        "SELECT lower(keyword_name), string_agg(DISTINCT keyword_category, '/' ORDER BY keyword_category) "
        "FROM duckdb_keywords() GROUP BY 1 ORDER BY 1"
    )
    return [(str(name), str(category)) for name, category in duckdb.sql(query).rows(connection)]  # type: ignore[arg-type]


def render(connection: object) -> str:
    """The module text for this engine's keywords."""
    rows = keywords(connection)
    if not rows:
        message = "duckdb_keywords() returned nothing"
        raise SystemExit(message)
    body = "".join(f'    "{name}": "{category}",\n' for name, category in rows)
    return HEADER + body + FOOTER


def main() -> int:
    """Write the module, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    import duckdb

    text = render(duckdb.connect())
    target = Path(__file__).resolve().parent.parent / "src" / "duckdb" / "_keywords.py"
    if args.check:
        if target.read_text() != text:
            print(f"{target} is stale; run scripts/gen_keywords.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f"wrote {target} ({text.count(chr(10)) - HEADER.count(chr(10)) - FOOTER.count(chr(10))} keywords)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
