name: Prepare DuckDB Python repository for building artifacts
description: This will checkout the repository, checkout the duckdb submodule, and create (local) tags if needed
inputs:
  git_ref:
    description: Git ref of the DuckDB python package
    default: refs/heads/main
    required: true
  duckdb_git_ref:
    description: Git ref of DuckDB
    default: refs/heads/main
    required: true
  artifact_type:
    description: Release type to build (nightly, rc, stable)
    required: true
    default: nightly

runs:
  using: composite
  steps:

    - name: Checkout DuckDB Python
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git_ref }}
        fetch-depth: 0
        submodules: true

    - name: Checkout DuckDB
      shell: bash
      run: |
        cd external/duckdb
        git fetch origin
        git checkout ${{ inputs.duckdb_git_ref }}
