"""
This module contains classes and methods related to functions and udf
"""

from __future__ import annotations
import typing

__all__: list[str] = ["ARROW", "DEFAULT", "FunctionNullHandling", "NATIVE", "PythonUDFType", "SPECIAL"]

class FunctionNullHandling:
    """
    Members:

      DEFAULT

      SPECIAL
    """

    DEFAULT: typing.ClassVar[FunctionNullHandling]  # value = <FunctionNullHandling.DEFAULT: 0>
    SPECIAL: typing.ClassVar[FunctionNullHandling]  # value = <FunctionNullHandling.SPECIAL: 1>
    __members__: typing.ClassVar[
        dict[str, FunctionNullHandling]
    ]  # value = {'DEFAULT': <FunctionNullHandling.DEFAULT: 0>, 'SPECIAL': <FunctionNullHandling.SPECIAL: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PythonUDFType:
    """
    Members:

      NATIVE

      ARROW
    """

    ARROW: typing.ClassVar[PythonUDFType]  # value = <PythonUDFType.ARROW: 1>
    NATIVE: typing.ClassVar[PythonUDFType]  # value = <PythonUDFType.NATIVE: 0>
    __members__: typing.ClassVar[
        dict[str, PythonUDFType]
    ]  # value = {'NATIVE': <PythonUDFType.NATIVE: 0>, 'ARROW': <PythonUDFType.ARROW: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

ARROW: PythonUDFType  # value = <PythonUDFType.ARROW: 1>
DEFAULT: FunctionNullHandling  # value = <FunctionNullHandling.DEFAULT: 0>
NATIVE: PythonUDFType  # value = <PythonUDFType.NATIVE: 0>
SPECIAL: FunctionNullHandling  # value = <FunctionNullHandling.SPECIAL: 1>
