name: Packaging
on:
  workflow_dispatch:
    inputs:
      minimal:
        type: boolean
        default: false
        description: Build a minimal set of wheels to do a sanity check
      testsuite:
        description: The tests that should be run
        required: true
        type: choice
        default: none
        options:
          - none
          - fast
          - all
      git_ref:
        type: string
        description: Git ref of the DuckDB python package
        default: refs/heads/main
      duckdb_git_ref:
        type: string
        description: Git ref of DuckDB
        default: refs/heads/main
      release_type:
        description: Release type to build
        required: true
        type: choice
        default: auto
        options:
          - auto
          - nightly_micro
          - nightly_minor
          - rc_micro
          - rc_minor
          - stable_micro
          - stable_minor

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-24.04
    outputs:
      summary: ${{ steps.sdist_summary.outputs.summary }}
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0
          submodules: true

      - name: Checkout DuckDB
        shell: bash
        run: |
          cd external/duckdb
          git fetch origin
          git checkout ${{ inputs.duckdb_git_ref }}

      - name: Install Astral UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.14"
          python-version: 3.11

      - name: Build sdist
        run: uv build --sdist

      - name: Install sdist
        run: |
          uv venv .test-env
          uv pip install --python .test-env ./dist/duckdb-*.tar.gz

      - name: Test sdist
        if: ${{ inputs.testsuite != 'none' }}
        shell: bash
        run: |
          # install the test requirements
          uv export --only-group test --no-hashes --no-emit-project > test-requirements.txt
          uv pip install --python .test-env -r test-requirements.txt 
          # run tests
          tests_dir="${{ github.workspace }}/tests${{ inputs.testsuite == 'fast' && '/fast' || '' }}"
          .test-env/bin/pytest ${tests_dir} --verbose --ignore=./tests/stubs

      - uses: actions/upload-artifact@v4
        with:
          name: sdist-main
          path: dist/*.tar.gz

      - name: Save summary
        id: sdist_summary
        run: |
          cd dist
          echo "summary=$(du -h -- *.tar.gz)" >> $GITHUB_OUTPUT

  build_wheels:
    name: 'Wheel: ${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}'
    strategy:
      matrix:
        python: [ cp39, cp310, cp311, cp312, cp313 ]
        platform:
          - { os: windows-latest,   arch: amd64,      cibw_system: win }
          - { os: ubuntu-24.04,     arch: x86_64,     cibw_system: manylinux }
          - { os: ubuntu-24.04,     arch: aarch64,    cibw_system: manylinux }
          - { os: macos-15,         arch: arm64,      cibw_system: macosx }
          - { os: macos-15,         arch: universal2, cibw_system: macosx }
          - { os: macos-13,         arch: x86_64,     cibw_system: macosx }
        minimal:
          - ${{ inputs.minimal }}
        exclude:
          - { minimal: true, python: cp310 }
          - { minimal: true, python: cp311 }
          - { minimal: true, python: cp312 }
          - { minimal: true, platform: { arch: aarch64 } }
          - { minimal: true, platform: { arch: universal2 } }
    runs-on: ${{ matrix.platform.os }}
    env:
      CIBW_TEST_SKIP: ${{ inputs.testsuite == 'none' && '*' || '*-macosx_universal2' }}
      CIBW_TEST_SOURCES: tests
      CIBW_TEST_GROUPS: test
      CIBW_TEST_COMMAND: uv run -v pytest ${{ inputs.testsuite == 'fast' && './tests/fast' || './tests' }} --verbose --ignore=./tests/stubs

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0
          submodules: true

      - name: Checkout DuckDB
        shell: bash
        run: |
          cd external/duckdb
          git fetch origin
          git checkout ${{ inputs.duckdb_git_ref }}

      - name: Set up QEMU only for (non-native) aarch64
        if: runner.os == 'Linux' && matrix.platform.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Install Astral UV, which will be used as build-frontend for cibuildwheel
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.14"
          enable-cache: true
          cache-suffix: -${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0
        env:
          CIBW_ARCHS: ${{ matrix.platform.arch == 'amd64' && 'AMD64' || matrix.platform.arch }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}
          path: wheelhouse/*.whl

      - name: Create summary
        run: |
          cd wheelhouse
          du -h -- *.whl > metadata-${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: metadata-${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}
          path: wheelhouse/metadata-${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

  summary:
    name: Build Summary
    runs-on: ubuntu-24.04
    needs: [build_sdist, build_wheels]
    if: always()
    steps:
      - name: Download wheel summaries
        uses: actions/download-artifact@v4
        with:
          pattern: metadata-*
          path: metadata
          merge-multiple: true

      - name: Summarize all
        shell: bash
        run: |
          to_table_row() { awk '{ print "|", $1, "|", $2, "|" }'; }
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Filesize | Filename |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.build_main_sdist.outputs.summary }}" | to_table_row >> $GITHUB_STEP_SUMMARY 
          for f in metadata/*; do
            cat $f | to_table_row >> $GITHUB_STEP_SUMMARY
          done
